Add support for Kotlin/Native in protocol
lavalink-devs/Lavalink pull request #1003
Opened 2024-01-26 15:59 UTC by DRSchlaubi

In preperation of Kord & Lavalink.kt adding support to Kotlin/Native this PR updates the protocol module accordingly

2025-04-02 00:31 UTC, DRSchlaubi commented
Ktor 3.1 released the changed required, would appriciate if we could release this at some point

2025-04-02 00:36 UTC, topi314 commented
So, does this still require a mac runner?

2025-04-02 00:39 UTC, DRSchlaubi commented
> So, does this still require a mac runner?

Not as of Kotlin 2.1.0: https://github.com/lavalink-devs/Lavalink/pull/1003#issuecomment-2770979323

2025-04-02 00:43 UTC, DRSchlaubi commented
Also macos runners are free for public projects

2025-04-02 07:59 UTC, topi314 requested changes

2025-04-02 07:59 UTC, topi314 commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.5-bin.zip
is this gradle downgrade needed?

2025-04-02 07:59 UTC, topi314 commented on gradle.properties
> +kotlin.native.enableKlibsCrossCompilation=true
can we put this somewhere else?
I'd rather not have the `gradle.properties` committed

2025-04-02 10:45 UTC, DRSchlaubi commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.5-bin.zip
I assume this happens when merging in master as master has updated the version since

2025-04-02 10:47 UTC, DRSchlaubi commented on gradle.properties
> +kotlin.native.enableKlibsCrossCompilation=true
The gradle.properties is supposed to be committed, ignoring it was wrong in the first place

2025-04-02 10:55 UTC, topi314 commented on gradle.properties
> +kotlin.native.enableKlibsCrossCompilation=true
Apparently user specific configuration should go into `~/.gradle/gradle.properties`.
Can you add that into the pr description?

2025-04-02 20:04 UTC, topi314 commented
this needs to be rebased, there are a lot of unrelated changes in here

2025-04-03 13:58 UTC, topi314 approved these changes

2025-04-03 13:59 UTC, merged