Update clients.md
lavalink-devs/Lavalink pull request #1034
Opened 2024-04-07 18:58 UTC by ftrapture

Added Blue.js Lavalink Client

2024-04-07 19:22 UTC, devoxin commented
I can't help but notice, is there any particular reason your account is only 3 hours old and there's no real commit history on your repo aside from "Add files via upload"?

Figured I should ask as it's a little strange.

2024-04-07 19:31 UTC, ftrapture commented
Oh hey, I actually just created a new account to add my newly updated code with a fresh startup. This is my old Git account where I already have the old version of the client source code: https://github.com/Web-chatsapp. Additionally, the commit history can be found here: https://github.com/ftrapture/blue.js/commits/main/
I hope you understand, looking forward to get accepted.
Thank you,

2024-04-12 22:45 UTC, topi314 requested changes

2024-04-12 22:45 UTC, topi314 commented on docs/clients.md
> +| [Blue.js](https://github.com/ftrapture/blue.js)                     | Node.js         | discord.js **V13** & **V14**               |                                |
this list is not alphabetically ordered, add yours at the end of all the `Node.js` clients

2024-04-18 09:12 UTC, closed without merging