Add sources tab to lavalink API documentation.
lavalink-devs/Lavalink pull request #1079
Opened 2024-07-20 14:07 UTC by mplatypus

Add sources tab to lavalinks API documentation pages.

2024-07-21 14:24 UTC, topi314 commented on docs/api/sources.md
> +```
this does not work for the new yt plugin you mentioned above

2024-07-21 14:28 UTC, mplatypus commented on docs/api/sources.md
> +```
Yes, I do know that, didn't change it/haven't yet. Can do tommorrow :D

2024-07-21 14:29 UTC, topi314 requested changes

2024-07-21 14:29 UTC, topi314 commented on docs/api/sources.md
> + - `ytmsearch`: This will search `music.youtube.com` for relevant tracks/playlists.
can you add the isrc syntax here? `ytsearch:"%ISRC%"`
also search results don't give back playlists
you should also add the `:` at the end I think
perhaps also that you put a search term behind the `:`
this needs to be added to all searches here

2024-07-21 14:29 UTC, topi314 commented on docs/api/sources.md
> + - `bcsearch`: This will search `bandcamp.com` for relevant tracks/playlists.
also no playlists & search term + `:`

2024-07-21 14:29 UTC, topi314 commented on docs/api/sources.md
> + - `scsearch`: This will search `soundcloud.com` for relevant tracks/playlists.
also no playlists & search term + `:`

2024-07-21 14:29 UTC, topi314 commented on docs/api/sources.md
> + - FIXME: add url's
pretty sure the current nico implementation doesn't work anymore, so you can ignore it until fixed

2024-12-07 16:23 UTC, topi314 commented
feel free to reopen if you feel like working on this again

2024-12-07 16:23 UTC, closed without merging