Add Plugin Update Checker
lavalink-devs/Lavalink pull request #1121
Opened 2024-12-10 02:53 UTC by Neuheit

Adds a plugin update checker function to `PluginManager.kt` that runs on application startup

Closes #1044

The function checks the maven repository of each plugin declaration and searches the maven metadata file for the latest version. If then compares the latest version and current version installed and writes to the console if the user needs to update. The 3rd party library "semver" is used as a dependency to compare versions.

2024-12-18 11:37 UTC, topi314 requested changes

2024-12-18 11:37 UTC, topi314 commented on LavalinkServer/build.gradle.kts
> +    implementation(libs.semver)
is this lib really needed? we already have a way to parse semver in https://github.com/lavalink-devs/Lavalink/blob/88cc85978198f75b662990b1ed0b0e9c77cd347b/protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/info.kt#L59

you would just need to add a method to compare them which should be easy

2024-12-18 11:37 UTC, topi314 commented on LavalinkServer/src/main/java/lavalink/server/bootstrap/PluginManager.kt
> +            }
Can you please not regex XML?
With #1049 we want to parse the `maven-metadata.xml` anyway

2024-12-18 17:22 UTC, Neuheit commented on LavalinkServer/build.gradle.kts
> +    implementation(libs.semver)
Oh I didnt see this thanks!

2024-12-28 19:52 UTC, topi314 commented on LavalinkServer/src/main/java/lavalink/server/bootstrap/PluginManager.kt
> +import javax.xml.parsers.DocumentBuilderFactory
wasn't this removed on java 11?
https://www.oracle.com/java/technologies/javase/11-relnote-issues.html#JDK-8190378

either [jackson xml](https://github.com/FasterXML/jackson-dataformat-xml) or [kotlinx.serialization](https://github.com/pdvrieze/xmlutil) should do the trick here

2024-12-30 18:17 UTC, Neuheit commented on LavalinkServer/src/main/java/lavalink/server/bootstrap/PluginManager.kt
> +import javax.xml.parsers.DocumentBuilderFactory
no that looks like it only affects the java namespace, javax looks like its untouched by that

2025-01-15 16:25 UTC, topi314 commented on LavalinkServer/src/main/java/lavalink/server/bootstrap/PluginManager.kt
> +import javax.xml.parsers.DocumentBuilderFactory
I'd rather have this use a modern lib like the above

2025-01-31 21:24 UTC, topi314 approved these changes
I went ahead and changed it to pdvrieze xmlutil, thanks

2025-01-31 21:25 UTC, merged