Add version flag
lavalink-devs/Lavalink pull request #121
Opened 2018-06-25 18:11 UTC by napstr

- Add CLI flag to print version information and exit
- Print more version information on start
- Print banner and version info into the log, not just standard out
- Log errors more reliably during spring application start

2018-06-25 18:14 UTC, CallMeCodeReview commented on LavalinkServer/src/main/java/lavalink/server/Launcher.java
> +            System.out.println("Version flag detected. Printing version info, then exiting.");
![Code Smell](https://sonarsource.github.io/sonar-github/code_smell.png 'Code Smell') Code Smell: Replace this use of System.out or System.err by a logger. ([squid:S106](https://sonarcloud.io/organizations/fredboat/rules#rule_key=squid%3AS106))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=lavalink%3ALavalink-Parent%3ALavalink-Server&pullRequest=121&issues=AWQ4JxbebXXTsx7OWMzy&open=AWQ4JxbebXXTsx7OWMzy)

[ISSUE_KEY]: AWQ4JxbebXXTsx7OWMzy

2018-06-25 18:14 UTC, CallMeCodeReview commented on LavalinkServer/src/main/java/lavalink/server/Launcher.java
> +            System.out.println(getVersionInfo());
![Code Smell](https://sonarsource.github.io/sonar-github/code_smell.png 'Code Smell') Code Smell: Replace this use of System.out or System.err by a logger. ([squid:S106](https://sonarcloud.io/organizations/fredboat/rules#rule_key=squid%3AS106))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=lavalink%3ALavalink-Parent%3ALavalink-Server&pullRequest=121&issues=AWQ4JxbebXXTsx7OWMzz&open=AWQ4JxbebXXTsx7OWMzz)

[ISSUE_KEY]: AWQ4JxbebXXTsx7OWMzz

2018-06-25 18:14 UTC, CallMeCodeReview commented on LavalinkServer/src/main/java/lavalink/server/Launcher.java
> +            System.out.println("Version info printed, exiting.");
![Code Smell](https://sonarsource.github.io/sonar-github/code_smell.png 'Code Smell') Code Smell: Replace this use of System.out or System.err by a logger. ([squid:S106](https://sonarcloud.io/organizations/fredboat/rules#rule_key=squid%3AS106))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=lavalink%3ALavalink-Parent%3ALavalink-Server&pullRequest=121&issues=AWQ4JxbebXXTsx7OWMz0&open=AWQ4JxbebXXTsx7OWMz0)

[ISSUE_KEY]: AWQ4JxbebXXTsx7OWMz0

2018-06-27 21:05 UTC, freyacodes requested changes

2018-06-27 21:05 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/Launcher.java
> +            System.out.println("Version info printed, exiting.");
These two other prints seem unnecessary, especially since having two makes them redundant.

2018-06-27 21:10 UTC, napstr commented on LavalinkServer/src/main/java/lavalink/server/Launcher.java
> +            System.out.println("Version info printed, exiting.");
How?

2018-06-27 21:12 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/Launcher.java
> +            System.out.println("Version info printed, exiting.");
If you are using the version flag, you should expect this to exit as it is common practice. I don't see a case where this would actually be useful

2018-06-27 21:13 UTC, napstr commented on LavalinkServer/src/main/java/lavalink/server/Launcher.java
> +            System.out.println("Version info printed, exiting.");
Nvm.

2018-06-27 21:13 UTC, napstr commented on LavalinkServer/src/main/java/lavalink/server/Launcher.java
> +            System.out.println("Version info printed, exiting.");
Brain was afk there ;)

2018-06-27 21:14 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/Launcher.java
> +            System.out.println("Version info printed, exiting.");
We've all been there :stuck_out_tongue:

2018-06-27 21:20 UTC, freyacodes approved these changes

2018-06-27 21:20 UTC, merged