Return FriendlyException message on LOAD_FAILED.
lavalink-devs/Lavalink pull request #174
Opened 2019-03-02 22:45 UTC by Devoxin

This PR aims to add in the functionality mentioned in #163. I also cleaned up how authorization is handled by using a Pre-Request filter, which removes the need to check authorization in the code of every endpoint.

When a request yields LOAD_FAILED, `exception` is returned in the response object. The other keys exist for the purpose of ensuring this is backwards-compatible change.

I'm not 100% sure on the implementation of how the exception is returned, so feedback is very much appreciated.

![](http://xtra.thicc-ho.es/83f3de49f0.png)

2019-03-03 00:19 UTC, schnapster requested changes

2019-03-03 00:19 UTC, napstr commented on LavalinkServer/src/main/java/lavalink/server/player/AudioLoaderRestHandler.java
> +@Configuration
Setting a "RequestAuthorizationFilter" has nothing to do with this specific RestHandler. It will also be applied to all endpoints, and is therefore highly misleading if it exists in this class. Probably best to be put into a standalone config class in the `lavalink.server.config` package.

2019-03-03 00:19 UTC, napstr commented on LavalinkServer/src/main/java/lavalink/server/io/RequestAuthorizationFilter.java
> +        if (authorization == null || !authorization.equals(serverConfig.getPassword())) {
This looks like it will break the debug endpoint which relies in a different password.

2019-03-03 00:21 UTC, napstr commented
Also this is missing an update of https://github.com/Frederikam/Lavalink/blob/master/IMPLEMENTATION.md

2019-03-03 00:23 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/io/RequestAuthorizationFilter.java
> +        if (authorization == null || !authorization.equals(serverConfig.getPassword())) {
The debug endpoint should probably be removed

2019-03-03 00:24 UTC, napstr commented
Personally I find the usefulness of a random plain string exception close to zero. Could you add an explain of the value of this PR?

2019-03-03 00:24 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/player/AudioLoaderRestHandler.java
> +@Configuration
Perhaps I'm just tired, but I'm not exactly sure what you mean?

2019-03-03 00:26 UTC, Devoxin commented
A load can fail when, for example, a video is unavailable due to region-blocking by copyright. I believe letting clients display a reason for not being able to load a track offers a slightly better user experience than a generic error of "Track couldn't be loaded", or nothing at all.

2019-03-03 00:27 UTC, napstr commented on LavalinkServer/src/main/java/lavalink/server/player/AudioLoaderRestHandler.java
> +@Configuration
A mix of Separation of Concerns and the Spring Boot docs.

2019-03-03 00:28 UTC, napstr commented
Displaying arbitrary strings that your receive from some api to endusers is a bad idea.

2019-03-03 00:31 UTC, Frederikam commented
@napstr I don't understand where you are coming from. Lots of protocols do that, such as with HTTP status strings and WS close reasons.

2019-03-03 00:32 UTC, Devoxin commented
I disagree. In cases where the video is from YouTube, Lavaplayer scrapes the exact reason YouTube provides to the user when viewed in an actual browser, so the messages should still be understandable to end users. Additionally I display such messages in my bot to users and have had 0 issues with it.

It's probably only a small thing but I think in cases where users try to play a certain track and it fails to load, a generic error of "Unable to load video" will probably make the user join the support server and ask why it failed, only to receive a canned response consisting of a list of reasons as to why it could've failed.

2019-03-03 00:40 UTC, napstr commented
My bad. I was under the impression these would by any kind of exceptions. However it is just the `FriendlyException`, whose class docs say:
>@param friendlyMessage A message which is understandable to end-users

2019-03-03 00:52 UTC, napstr commented
What do you think about including the [severity](https://github.com/sedmelluq/lavaplayer/blob/master/main/src/main/java/com/sedmelluq/discord/lavaplayer/tools/FriendlyException.java#L10)?

```json
  "loadType": "LOAD_FAILED",
  "playlistInfo": {},
  "tracks": [],
  "exception": {
    friendlyMessage: "The uploader has not made this video available in your country."
    severity: "COMMON"
  }
```

2019-03-03 00:59 UTC, Devoxin commented
Not too sure about that one, might be useful for developers as an indicator of how severe the exception is but other than that it's probably a little useless, although I've no objections to including that in the response.

2019-03-08 16:51 UTC, freyacodes requested changes

2019-03-08 16:51 UTC, Frederikam commented on IMPLEMENTATION.md
> +    "friendlyMessage": "The uploader has not made this video available in your country.",
This should probably just be `message`

2019-03-08 16:51 UTC, Frederikam commented on IMPLEMENTATION.md
> +    "severity": "COMMON"
Severity should be explained

2019-03-08 16:51 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/io/RequestAuthorizationFilter.java
> +            log.warn("Authorization failed");
This should probably log the IP and request path

2019-03-08 16:51 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/player/AudioLoaderRestHandler.java
> +public class AudioLoaderRestHandler implements WebMvcConfigurer {
`AudioLoaderRestHandler` affects ALL RestControllers. It is misleading to do the configuration from this class, and it should be done by an `@Configuration` class in the config package.

2019-03-08 16:51 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/player/LoadResult.java
> +                      @Nullable FriendlyException exception) {
`exception` is mutually exclusive to all other parameters besides `loadResultType`, so a separate constructor is preferred.

2019-03-08 16:52 UTC, Frederikam commented on IMPLEMENTATION.md
> +    "friendlyMessage": "The uploader has not made this video available in your country.",
You might want to otherwise document that the message is okay to show end-users

2019-03-08 21:40 UTC, schnapster approved these changes

2019-04-02 13:09 UTC, freyacodes approved these changes

2019-04-02 13:09 UTC, merged