Add Friendly exception to TrackExceptionEvent
lavalink-devs/Lavalink pull request #201
Opened 2019-06-14 08:13 UTC by duncte123

This PR adds the FriendlyException from lava player to the TrackExceptionEvent so the java client can make use of this and return the correct severity.

Example output: (tested with the lofi hip hop radio stream)
```json
{
  "exception": {
    "severity": "FAULT",
    "cause": "org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected",
    "message": "Something went wrong when decoding the track."
  },
  "op": "event",
  "type": "TrackExceptionEvent",
  "track": "QAAAkAIALGxvZmkgaGlwIGhvcCByYWRpbyAtIGJlYXRzIHRvIHJlbGF4L3N0dWR5IHRvAApDaGlsbGVkQ293f/////////8AC2hIVzFvWTI2a3hRAQEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9aEhXMW9ZMjZreFEAB3lvdXR1YmUAAAAAAAAX/A==",
  "error": "Something went wrong when decoding the track.",
  "guildId": "191245668617158656"
}
``` 

Closes #198

2019-06-15 17:33 UTC, freyacodes requested changes
This will have to be documented, particularly with the deprecation of error in the next API version

2019-06-15 17:33 UTC, Frederikam commented on IMPLEMENTATION.md
> +                        new Exception(jsonEx.getString("cause"))
Should probably be `RuntimeException`

2019-06-16 09:34 UTC, freyacodes requested changes

2019-06-16 09:34 UTC, Frederikam commented on IMPLEMENTATION.md
> +## Significant changes v3.0 -> v3.1
As per our policy, this API breaking change would warrant an API bump to v4.0.
```suggestion
## Significant changes v3.0 -> v4.0
```

2019-06-16 09:37 UTC, duncte123 commented on IMPLEMENTATION.md
> +## Significant changes v3.0 -> v3.1
Mixed up api and major, mb

2019-06-16 09:40 UTC, Frederikam commented
Here's what I'll do. I'll create a new branch for you called something like `nextapi` or something. Then I'll merge this PR into that as a v4 branch. 

This will allow me to publish a v4 snapshot version without formally releasing v4.

2019-06-16 09:47 UTC, duncte123 commented
> Here's what I'll do. I'll create a new branch for you called something like `nextapi` or something. Then I'll merge this PR into that as a v4 branch.
> 
> This will allow me to publish a v4 snapshot version without formally releasing v4.

Sounds good to me

2019-06-16 09:54 UTC, freyacodes approved these changes

2019-06-16 09:54 UTC, merged