RotateOnBan LP + rotateOnBan config
lavalink-devs/Lavalink pull request #230
Opened 2019-10-18 08:01 UTC by ByteAlex

Title says it all, I wasn't able to fully test it locally, cause my IPv6 subnet wasn't setup properly, but maybe you can give it a short test (or I'll do as soon as I get a working IPv6 subnet)

2019-10-18 17:54 UTC, Frederikam commented on LavalinkServer/application.yml.example
> +      #ipVersion: '6'
It would be nice if Lavalink would just detect which family

2019-10-20 16:29 UTC, freyacodes requested changes

2019-10-20 16:29 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/config/RoutePlannerService.kt
> +class RoutePlannerService(rateLimitConfig: RateLimitConfig) {
This should probably be merged with `AudioPlayerConfiguration`

The route planner is practically a part of the player config.

2019-10-20 16:29 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/config/RoutePlannerService.kt
> +    private final val routePlanner: AbstractRoutePlanner?
This is redundant. Just use one bean function. The bean will just be run once.

2019-10-20 16:29 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/config/RoutePlannerService.kt
> +                rateLimitConfig.strategy == "RotateOnBan" -> RotatingIpRoutePlanner(ipBlock, filter)
Trim and ignore this string for good measure.

2019-10-20 16:29 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/config/RoutePlannerService.kt
> +        routePlanner = if(rateLimitConfig.ipBlock.isNotEmpty()) {
You could add `if(rateLimitConfig.ipBlock.isEmpty()) return null` (in a function) and save the long if block.

2019-10-20 16:29 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/config/RoutePlannerService.kt
> +class RoutePlannerService(rateLimitConfig: RateLimitConfig) {
`RateLimitConfig` can probably be null. Should be `RateLimitConfig?` unless you want old configs to break.

2019-10-20 16:29 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/player/RoutePlannerRestHandler.java
> +public final class RoutePlannerRestHandler {
These routes should be documented

2019-10-20 16:29 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/player/RoutePlannerRestHandler.java
> +            final InetAddress address = InetAddress.getByAddress(Base64.getDecoder().decode(ip));
Why base64?

2019-10-20 16:29 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/player/RoutePlannerRestHandler.java
> +    public ResponseEntity<String> freeSingleIp(HttpServletRequest request, @RequestParam String ip) {
This should be a POST request. Don't use a request parameter, use a body.

2019-10-20 16:29 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/player/RoutePlannerRestHandler.java
> +        final AbstractRoutePlanner activePlanner = AbstractRoutePlanner.getActivePlanner();
This looks like static abuse. Could you not just get the planner from dependency injection?

2019-10-20 16:29 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/player/RoutePlannerRestHandler.java
> +public final class RoutePlannerRestHandler {
Also, is this endpoint subject to authentication?

2019-10-22 13:48 UTC, freyacodes requested changes
Looks mostly good. I am still skeptical of the static abuse in Lavaplayer.

2019-10-26 02:57 UTC, itslukej commented
I think it would be important to note in the readme that Linux AnyIP should be configured on the CIDR block for correct operation.

https://blog.widodh.nl/2016/04/anyip-bind-a-whole-subnet-to-your-linux-machine/
https://blog.cloudflare.com/how-we-built-spectrum/#assigningmillionsofipstoaserver

2019-10-29 21:11 UTC, ByteAlex commented
Static abuse in Lavaplayer was removed, yet sedmelluq will change the implementation a little bit, but as far as I understood he will merge my PR

2019-11-07 13:35 UTC, ByteAlex commented
Uses official LP release now with latest versions @Frederikam

2019-11-07 13:44 UTC, ByteAlex commented
* Added ratelimit config section
* When ratelimit config is set up, a AbstractRoutePlanner is initialized from it (according to the strategy) and the YoutubeRotator extension from lavaplayer will be set up with it
* Added RoutePlannerRestHandler (For monitoring RoutePlanner statistics / bans)

2019-11-10 13:38 UTC, freyacodes requested changes
All configuration properties and REST endpoints need to be documented.

2019-11-10 13:38 UTC, Frederikam commented on LavalinkServer/application.yml.example
> +      #ipBlocks: ["127.0.0.1/31", "127.0.0.3/32"]
These are poor examples

2019-11-10 13:38 UTC, Frederikam commented on LavalinkServer/application.yml.example
> +      #strategy: 'RotateOnBan' # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
Use double quotes here for consistency

2019-11-10 13:38 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/config/AudioPlayerConfiguration.kt
> +                YoutubeIpRotator.setup(youtube, routePlanner)
So we're back to static abuse now? Even if this is lavaplayer it still concerns me.

2019-11-10 13:38 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/config/AudioPlayerConfiguration.kt
> +        val ipBlockList = ArrayList(rateLimitConfig.ipBlocks)
Avoid the use of `ArrayList` in Kotlin. Convert to a mutable list instead.

2019-11-10 13:38 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/config/AudioPlayerConfiguration.kt
> +            log.warn("Usage of deprecated `ipBlock` found, please use `ipBlocks` list instead!")
Don't add legacy support for something that was not formally released.

2019-11-10 13:38 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/config/AudioPlayerConfiguration.kt
> +            log.debug("List of ip blocks is empty, skipping setup of route planner")
Consider using info logging

2019-11-10 13:38 UTC, Frederikam commented on LavalinkServer/application.yml.example
> +    ratelimit:
Should probably also be commented out

2019-11-10 13:38 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/config/ServerConfig.kt
> -    var excludedIps: List<String> = emptyList()
It would make sense to add `RateLimitConfig` here

2019-11-10 13:38 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/routeplanner/RoutePlannerRestHandler.kt
> +            jsonObject.put("status", "E")
Use HTTP status codes instead of this

2019-11-10 13:38 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/routeplanner/RoutePlannerRestHandler.kt
> +        return ResponseEntity.ok(jsonObject.toString())
I believe `#toString()` is redundant

2019-11-10 13:38 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/routeplanner/RoutePlannerRestHandler.kt
> +            routePlanner?.freeAddress(address)
Use `!!` not `?.`

2019-11-10 13:38 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/routeplanner/RoutePlannerRestHandler.kt
> +        } catch (exception: UnknownHostException) {
Just let Spring handle the `UnknownHostException`

2019-11-10 13:38 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/routeplanner/RoutePlannerRestHandler.kt
> +    fun freeSingleAddress(request: HttpServletRequest, @RequestBody requestBody: String): ResponseEntity<String> {
Request body should be a POJO

2019-11-10 13:38 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/routeplanner/RoutePlannerRestHandler.kt
> +    fun freeAllAddresses(request: HttpServletRequest, @RequestBody requestBody: String): ResponseEntity<String> {
`requestBody` is unused

2019-11-10 13:38 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/routeplanner/RoutePlannerRestHandler.kt
> +            jsonObject.put("message", "address successfully unmarked")
Inconsistent capitalization

2019-11-10 13:38 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/routeplanner/RoutePlannerRestHandler.kt
> +            routePlanner?.freeAllAddresses()
Don't use `?.`

2019-11-10 13:38 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/routeplanner/RoutePlannerRestHandler.kt
> +class RoutePlannerRestHandler(val routePlanner: AbstractRoutePlanner?) {
Consider replacing all JSON with POJOs. Let Spring deal with all the (de)serialization.

2019-11-10 13:38 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/routeplanner/RoutePlannerRestHandler.kt
> +        if (planner is RotatingIpRoutePlanner) {
Replace if statements with `when`

2019-11-10 13:38 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/routeplanner/RoutePlannerRestHandler.kt
> +            jsonObject.put("estAddressIndex", planner.currentAddress)
No idea what `estAddressIndex` means

2019-11-10 13:38 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/routeplanner/RoutePlannerRestHandler.kt
> +        ipBlockJson.put("type", ipBlock?.type?.simpleName ?: "Error")
Consider using null instead of `Error`

2019-11-10 13:39 UTC, Frederikam commented
> Added RoutePlannerRestHandler (For monitoring RoutePlanner statistics / bans)

If you want to be able to monitor these things, you should consider adding Prometheus support

2019-11-11 16:12 UTC, closed without merging

2019-11-11 16:13 UTC, Frederikam commented
Hey what happened to the fork and this PR?

2019-11-12 11:59 UTC, ByteAlex commented on LavalinkServer/src/main/java/lavalink/server/config/AudioPlayerConfiguration.kt
> +                YoutubeIpRotator.setup(youtube, routePlanner)
It's based on sed's decision. He implemented it like that