Emit TrackStartEvent
lavalink-devs/Lavalink pull request #242
Opened 2019-12-16 12:35 UTC by duncte123

2020-01-24 20:52 UTC, freyacodes requested changes
Needs documentation in IMPLEMENTATION.md

2020-01-24 20:52 UTC, Frederikam commented on CHANGELOG.md
> +## v3.2.2
Don't edit this file

2020-01-25 13:47 UTC, duncte123 commented on CHANGELOG.md
> +## v3.2.2
I'll revert it

2020-01-25 13:53 UTC, duncte123 commented
> Needs documentation in IMPLEMENTATION.md

Where would you like me to document this as I cannot find any documentation for the other events in there

2020-01-27 13:29 UTC, Frederikam commented
It's given as a Java example in IMPLEMENTATION.md.

Not pretty, but it's there.

2020-01-27 14:53 UTC, duncte123 commented
> It's given as a Java example in IMPLEMENTATION.md.
> 
> Not pretty, but it's there.

Then this is already present, it is the first file in the changes tab.

2020-01-27 14:54 UTC, Frederikam commented
My bad. I must have assumed I was looking at actual source code.

2020-01-27 14:55 UTC, freyacodes approved these changes

2020-01-27 14:55 UTC, merged