Replace Magma with Koe
lavalink-devs/Lavalink pull request #269
Opened 2020-04-10 12:15 UTC by Frederikam

Koe is a smaller and perhaps more maintainable alternative to Magma.

Koe also relies on JDA-NAS natives for native audio sending.

2020-04-18 05:06 UTC, Dramex commented
^ green circle lights up when joining a channel without playing a song.

2020-04-18 08:26 UTC, Frederikam commented
@Dramex I haven't encountered that. Can you provide a log?

2020-04-18 08:35 UTC, Dramex commented
@Frederikam https://pastebin.com/raw/NdHhX9YU

2020-04-18 12:16 UTC, Frederikam commented
@Dramex you're not playing anything.

Though it is odd that there is a green circle. Maybe that's because this version of Koe does not send silent frames.

2020-04-19 00:21 UTC, alula commented
I'm working on it, Koe's handling of speaking is currently broken.

2020-04-19 02:41 UTC, alula commented
@Frederikam https://github.com/KyokoBot/koe/releases/tag/1.0.0-beta1

2020-05-09 21:22 UTC, Frederikam commented
Finally got around to fixing the breaking changes.

I haven't found the time to test it. Feedback is appreciated.

2020-05-10 09:22 UTC, Intuinewin requested changes

2020-05-10 09:22 UTC, Antoineone commented on LavalinkServer/src/main/java/lavalink/server/player/Player.java
> +        new Provider(connection);
```suggestion
        connection.setAudioSender(new Provider(connection));
```

2020-05-10 10:05 UTC, Frederikam commented on LavalinkServer/src/main/java/lavalink/server/player/Player.java
> +        new Provider(connection);
Nice catch

2020-05-11 13:02 UTC, Frederikam commented
I am now using this in production. This is probably safe to use.

2020-05-11 13:02 UTC, merged