Add support for endTime
lavalink-devs/Lavalink pull request #315
Opened 2020-06-18 20:52 UTC by Neuheit

This PR fixes #179, and makes end time functional.

The only thing I am not sure about is handling the seek portion. Right now it will end the track if the seek position is greater than the endtime position, but perhaps it should just cancel the marker and keep the track playing.

2020-06-18 21:31 UTC, devoxin requested changes

2020-06-18 21:31 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/io/WebSocketHandlers.kt
> +        if (json.has("stopTime")) {
As per the [IMPLEMENTATION.md](https://github.com/Frederikam/Lavalink/blob/master/IMPLEMENTATION.md), this should be `endTime`.

2020-06-18 21:31 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/io/WebSocketHandlers.kt
> +            val stopTime = json.getLong("stopTime")
See above comment.

2020-06-18 21:37 UTC, Devoxin commented
> The only thing I am not sure about is handling the seek portion. Right now it will end the track if the seek position is greater than the endtime position, but perhaps it should just cancel the marker and keep the track playing

Lavaplayer automatically handles this. When a seek is requested that exceeds the marker position, the marker handler will be invoked with a state denoting so. I believe this should already be handled [by the `BYPASSED` check](https://github.com/Frederikam/Lavalink/blob/master/LavalinkServer/src/main/java/lavalink/server/player/TrackEndMarkerHandler.java#L37), where `BYPASSED` is the state provided when the marker position is exceeded, as [denoted here](https://github.com/sedmelluq/lavaplayer/blob/master/main/src/main/java/com/sedmelluq/discord/lavaplayer/track/TrackMarkerHandler.java#L29).

My only concern is the MarkerHandler line linked above (L37).
`if (state.equals(MarkerState.REACHED) | state.equals(MarkerState.BYPASSED))` should perhaps be `if (state.equals(MarkerState.REACHED) || state.equals(MarkerState.BYPASSED))` instead.

2020-07-13 09:51 UTC, freyacodes reviewed
The code looks fine, but has this been tested?

2020-07-13 13:10 UTC, Neuheit commented
> 
> 
> The code looks fine, but has this been tested?

Yes it has. It works fine both without and endtime and with and endtime. Passing in an endtime ends it as expected.

2020-07-13 13:11 UTC, freyacodes approved these changes
:ok_hand:

2020-07-13 13:11 UTC, merged