Updated the documentation to a certain extent
lavalink-devs/Lavalink pull request #379
Opened 2020-10-28 12:01 UTC by ThatAnonymousG

Updated the documentation for the OP play payload and a few other stuff.

2020-10-28 12:55 UTC, Frederikam requested changes

2020-10-28 12:55 UTC, Frederikam commented on IMPLEMENTATION.md
> +#### Provides a voice update
```suggestion
#### Provide a voice update
```
Wrong tense

2020-10-28 12:55 UTC, Frederikam commented on IMPLEMENTATION.md
> +#### Plays a track
```suggestion
#### Play a track
```
Wrong tense

2020-10-28 12:55 UTC, Frederikam commented on IMPLEMENTATION.md
> +`volume` is an optional setting which determines the default volume of the player.
```suggestion
`volume` is an optional setting which changes the volume if provided.
```

2020-10-28 12:55 UTC, Frederikam commented on IMPLEMENTATION.md
> +If `pause` is set to true, the playback will be paused by default. This is an optional field.
```suggestion
If `pause` is set to true, the playback will be paused. This is an optional field.
```

2020-10-28 12:55 UTC, Frederikam commented on IMPLEMENTATION.md
>  #### RoutePlanner Status
```suggestion
#### Get RoutePlanner status
```

2020-11-09 17:20 UTC, ThatAnonymousG commented
I accepted all the suggestions. Sorry for the delay in replying.

2020-11-09 17:21 UTC, Frederikam approved these changes
Thanks!

2020-11-09 17:21 UTC, merged