source name in track info
lavalink-devs/Lavalink pull request #478
Opened 2021-04-18 16:46 UTC by TopiSenpai

the track source name is already given in the raw track data and should be useful to also have in the `/loadtracks`, `/decodetrack` & `/decodetracks` endpoints

2021-04-18 23:35 UTC, freyacodes requested changes
The documentation should reflect how multiple endpoints are being changed

2021-04-18 23:36 UTC, freyacodes commented
(Might want to cherrypick 3c16516)

2021-04-19 22:07 UTC, TopiSenpai commented
wanna cherrypick https://github.com/freyacodes/Lavalink/pull/480 after being merged :)

2021-04-20 20:21 UTC, freyacodes approved these changes

2021-04-20 20:21 UTC, merged