feat: http proxy config for httpAudioSourceManager
lavalink-devs/Lavalink pull request #595
Opened 2022-01-06 03:44 UTC by ToxicMushroom

Useful for stopping bad actors from IP-grabbing your main music server and attacking it.
Tested with squidproxy

2022-01-06 03:51 UTC, Walkyst commented
How it supposed to connect if proxy behind some basic auth like login and password?

2022-01-06 12:34 UTC, ToxicMushroom commented
> How it supposed to connect if proxy behind some basic auth like login and password?
I've added an option for authentication, I don't have a setup to test this though

2022-01-06 13:18 UTC, freyacodes requested changes

2022-01-06 13:18 UTC, freyacodes commented on LavalinkServer/application.yml.example
> +      #proxyPort: 3128
This needs to be documented with comments, and this is missing username and password

2022-01-07 11:15 UTC, freyacodes commented
It still needs a description of why you would ever want to set up a proxy

2022-01-07 15:18 UTC, freyacodes approved these changes

2022-01-07 15:19 UTC, merged