feat: allow plugins to modify /loadtracks response
lavalink-devs/Lavalink pull request #618
Opened 2022-02-09 10:22 UTC by melike2d

Added the ability for plugins to modify the `playlistInfo` and `tracks[*].info` objects returned by /loadtracks.

- adds a interface to the plugin api: `AudioLoaderJsonModifier`.
- converts `AudioLoaderRestHandler` and `LoadResult` to kotlin so that I could keep my sanity.
- adds `lavalink.server.allowTrackModifications` to prevent clients from breaking (defaults to false).

2022-02-09 12:08 UTC, freyacodes commented
This looks like an interesting addition. I'm currently very busy, so don't expect a proper review before the 25th of February

2022-03-16 13:31 UTC, freyacodes requested changes
It looks like `AudioLoaderJsonModifier` is invoked when it's either a bean or when the audio source manager is an implementation of it. This seems unnecessarily convoluted:

* It means that the same modifier can be invoked twice for the same object, especially as audio source managers are often provided as beans.
* It doesn't add much value as modifiers can already be made to only target specific types of managers or track types
* It's confusing, and it's not even documented

2022-03-16 13:31 UTC, freyacodes commented on IMPLEMENTATION.md
> +If enabled by the `lavalink.server.allowTrackModifications` config value, any installed plugins may modify the contents of `playlistInfo` and each `info` object for a track
I think I see where you are coming from but I don't like this. Plugins should be allowed to break the API if they so wish.

2022-03-16 13:31 UTC, freyacodes commented on LavalinkServer/src/main/java/lavalink/server/player/AudioLoaderRestHandler.kt
> +/*
It's difficult to review this code because you converted the file to Kotlin in while in the same commit you implemented the feature

2022-03-16 13:31 UTC, freyacodes commented on plugin-api/src/main/java/dev/arbjerg/lavalink/api/AudioLoaderJsonModifier.java
> + */
This should document how to use it with a bean

2022-03-16 13:31 UTC, freyacodes commented on LavalinkServer/src/main/java/lavalink/server/player/AudioLoaderRestHandler.kt
> +                .runCatching { modifier.block(this) }
This looks like it will swallow the error without logging it. A simple try/catch would probably be a better and simpler alternative to this method

2022-03-16 14:09 UTC, viztea commented
> It means that the same modifier can be invoked twice for the same object, especially as audio source managers are often provided as beans.

> It doesn't add much value as modifiers can already be made to only target specific types of managers or track types

True, I forget the reason I did this but it's definitely an overlook on my part.

> It's confusing, and it's not even documented

As in not documented in the `PLUGINS.md`? I could write docs for it.

2022-03-16 14:12 UTC, melike2d commented on LavalinkServer/src/main/java/lavalink/server/player/AudioLoaderRestHandler.kt
> +/*
Yeah sorry :/

2022-03-17 11:54 UTC, freyacodes commented
> As in not documented in the PLUGINS.md? I could write docs for it.

That would be nice as well but I was more thinking about the documentation in the interface

2022-06-20 15:40 UTC, closed without merging