Allow adding new MediaContainerProbes via plugins
lavalink-devs/Lavalink pull request #631
Opened 2022-03-08 03:48 UTC by TheEssem

Just a small edit to `AudioPlayerConfiguration` that adds the ability to add new `MediaContainerProbe` instances. This is useful for adding support for new HTTP/local file formats or adding a new source that depends on some sort of weird codec.

2022-03-16 12:55 UTC, freyacodes commented on LavalinkServer/src/main/java/lavalink/server/config/AudioPlayerConfiguration.kt
> +        if (sources.isLocal) audioPlayerManager.registerSourceManager(LocalAudioSourceManager(mcr))
Is this additive? Are the default probes removed if the collection is empty?

2022-03-16 13:04 UTC, melike2d commented on LavalinkServer/src/main/java/lavalink/server/config/AudioPlayerConfiguration.kt
> +        if (sources.isLocal) audioPlayerManager.registerSourceManager(LocalAudioSourceManager(mcr))
> Is this additive?

Nope

2022-03-16 15:45 UTC, TheEssem commented on LavalinkServer/src/main/java/lavalink/server/config/AudioPlayerConfiguration.kt
> +        if (sources.isLocal) audioPlayerManager.registerSourceManager(LocalAudioSourceManager(mcr))
No, LocalAudioSourceManager when initialized uses the default probe list and `MediaContainerRegistry#extended()` simply adds onto the default probe list.

2022-03-17 08:18 UTC, freyacodes commented on LavalinkServer/src/main/java/lavalink/server/config/AudioPlayerConfiguration.kt
> +        if (sources.isLocal) audioPlayerManager.registerSourceManager(LocalAudioSourceManager(mcr))
Ah yes, I see

2022-03-17 08:19 UTC, freyacodes requested changes
This feature needs to be documented in PLUGINS.md otherwise plugin developers have no chance of knowing about it

2022-05-22 21:14 UTC, TheEssem commented
Sorry about that, not sure how it closed itself.

2022-06-10 18:13 UTC, freyacodes approved these changes
Thanks! Sorry for the wait

2022-06-10 18:14 UTC, merged