implement rest routes for ws ops
lavalink-devs/Lavalink pull request #748
Opened 2022-09-20 02:24 UTC by TopiSenpai

ToDo:
- [ ] `GET`      `/v3/sessions/{sessionId}/players/{playerId}`
- [ ] `PATCH`  `/v3/sessions/{sessionId}/players/{playerId}`
- [ ] `DELETE` `/v3/sessions/{sessionId}/players/{playerId}`
- [ ] `GET`      `v3/sessions/{sessionId}/players` ?
- [ ] `PATCH`  `v3/sessions/{sessionId}`

- [ ] add new ws op to communicate `sessionId` & `resumed`

- [ ] move all routes to `/v3` prefix & deprecate old
- [ ] deprecate ws commands

- [ ] docs for everything

2022-10-26 21:22 UTC, TopiSenpai commented
This is prob in a kind of usable state now
I haven't tested the new rest api too much but at least the old part works

2022-10-26 21:27 UTC, TopiSenpai commented
This also introduces the protocol sub project which can be used by any jvm lavalink client to deserialize & serialize objects to json
This can be imported via 
```groovy
implementation("com.github.freyacodes.Lavalink:protocol:LATEST_COMMIT_HASH")
```

2022-10-27 08:49 UTC, Drapersniper commented
Response from the `/v3/info` endpoint - plugin data is missing
```
{
	'version': {
		'semver': 'e5e356c93586a75df26375ea5f5b0e5da77ac4e1-SNAPSHOT',
		'major': 0,
		'minor': 0,
		'patch': 0,
		'preRelease': None
	},
	'buildTime': 1666828697261,
	'git': {
		'branch': 'feature/rest-api',
		'commit': 'e5e356c',
		'commitTime': 1666828648000
	},
	'jvm': '13.0.13',
	'lavaplayer': '1.3.98.4-original',
	'sourceManagers': ['youtube', 'soundcloud', 'bandcamp', 'twitch', 'vimeo', 'beam.pro', 'local', 'getyarn.io', 'clypit', 'speak', 'pornhub', 'reddit', 'ocremix', 'tiktok', 'mixcloud', 'soundgasm', 'spotify', 'applemusic', 'deezer', 'http'],
	'plugins': [{
		'plugins': []
	}, {
		'plugins': []
	}, {
		'plugins': []
	}, {
		'plugins': []
	}, {
		'plugins': []
	}]
}
```

2022-10-27 09:40 UTC, Drapersniper commented
GET `/v3/stats` not found

GET `/v3/decodetrack?encodedTrack=` raises a 500 Internal server error

GET `/v3/decodetrack?track=` raises a 404 - Required request parameter 'encodedTrack' for method parameter type String is not present

GET `/v3/loadtracks?identifier=` response always contains an `exception` object

POST `/v3/routeplanner/free/all` fails with 500 - Required request body is missing: public org.springframework.http.ResponseEntity<java.lang.Void> lavalink.server.io.RoutePlannerRestHandler.freeSingleAddress(javax.servlet.http.HttpServletRequest,dev.arbjerg.lavalink.protocol.RoutePlannerFreeAddress) (According to documentation there is no body required for this endpoint)

POST `/routeplanner/free/address` fails with 500, nothing in logs

2022-10-27 12:11 UTC, Drapersniper commented
GET `/v3/sessions/7g8qruri2ujnfnsf/players` returns a 404

PATCH `v3/sessions/fjbl5mfcm4e1fol8/players/{guildId}` returns a 500 when starting a track

```json
// Payload
{
    "encodedTrack": "QAAA3gIAD015c3Rlcnkgb2YgTG92ZQAOU3VmamFuIFN0ZXZlbnMAAAAAAAPMgAAWNUdiVnpjNkV4NUxZbExKcXpSUWh1eQABADVodHRwczovL29wZW4uc3BvdGlmeS5jb20vdHJhY2svNUdiVnpjNkV4NUxZbExKcXpSUWh1eQAHc3BvdGlmeQEADFVTNjRHMTczNzMwMgEAQGh0dHBzOi8vaS5zY2RuLmNvL2ltYWdlL2FiNjc2MTZkMDAwMGIyNzMzZmMxNTg4ODAzZDE4ODdmMTFkNjYwY2MAAAAAAAAAAA==",
    "startTime": 445
}
// Response
{
    "timestamp": "2022-10-27T11:53:55.329+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "path": "/v3/sessions/fjbl5mfcm4e1fol8/players/OBFUSCATED"
}

```
```
2022-10-27 12:53:55.342  INFO 3484832 --- [XNIO-1 task-2] lavalink.server.io.SessionRestHandler    : PATCH /v3/sessions/fjbl5mfcm4e1fol8/players/OBFUSCATED: PlayerUpdate(encodedTrack=QAAA3gIAD015c3Rlcnkgb2YgTG92ZQAOU3VmamFuIFN0ZXZlbnMAAAAAAAPMgAAWNUdiVnpjNkV4NUxZbExKcXpSUWh1eQABADVodHRwczovL29wZW4uc3BvdGlmeS5jb20vdHJhY2svNUdiVnpjNkV4NUxZbExKcXpSUWh1eQAHc3BvdGlmeQEADFVTNjRHMTczNzMwMgEAQGh0dHBzOi8vaS5zY2RuLmNvL2ltYWdlL2FiNjc2MTZkMDAwMGIyNzMzZmMxNTg4ODAzZDE4ODdmMTFkNjYwY2MAAAAAAAAAAA==, identifier=OMITTED, position=445, endTime=OMITTED, volume=OMITTED, paused=OMITTED, filters=OMITTED, voice=OMITTED)
2022-10-27 12:53:55.342  INFO 3484832 --- [XNIO-1 task-2] lavalink.server.io.SessionRestHandler    : Received encodedTrack request for guild OBFUSCATED
2022-10-27 12:53:55.343 ERROR 3484832 --- [XNIO-1 task-2] io.undertow.request                      : UT005023: Exception handling request to /v3/sessions/fjbl5mfcm4e1fol8/players/OBFUSCATED

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalStateException: Not present
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:880) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[jakarta.servlet-api-4.0.4.jar!/:4.0.4]
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at lavalink.server.io.ResponseHeaderFilter.doFilterInternal(ResponseHeaderFilter.kt:17) ~[classes!/:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar!/:5.3.18]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.18.jar!/:5.3.18]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar!/:5.3.18]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.18.jar!/:5.3.18]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar!/:5.3.18]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.18.jar!/:5.3.18]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar!/:5.3.18]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.core.ContextCl [...]

2022-11-09 20:30 UTC, TopiSenpai commented
alright I think all proposed changes from https://github.com/freyacodes/Lavalink/pull/750 are now implemented
You can grab the newest jar from the github actions.
Feel free to report all bugs or other things you may find here.

2022-11-09 20:41 UTC, ooliver1 commented on CHANGELOG.md
> +## 3.6.1
Shouldn't this be in a separate PR, for scope yaknow

2022-11-09 20:43 UTC, TopiSenpai commented on CHANGELOG.md
> +## 3.6.1
oh the base branch (v3.6) is outdated :D

2022-11-10 16:56 UTC, flav28 commented
Change the name of the argument "noReplace" to "replace" it's more logical

2022-11-10 17:11 UTC, TopiSenpai commented
> Change the name of the argument "noReplace" to "replace" it's more logical

that should go into https://github.com/freyacodes/Lavalink/pull/750

2022-11-13 21:19 UTC, Drapersniper commented
Seeing this with the build from [9228b4f32fe5fa5039812f8eaa0d307c2283fe15](https://github.com/freyacodes/Lavalink/pull/748/commits/9228b4f32fe5fa5039812f8eaa0d307c2283fe15)

```
2022-11-13 20:55:26.578  INFO 75000 --- [XNIO-1 task-1] lavalink.server.io.RequestLoggingFilter  : PATCH /v3/sessions/p1vwf8ltrm9ngu3y/players/133049272517001216?noReplace=false, client=127.0.0.1, payload={"encodedTrack":"QAAAygIABUdPISEhAARGTE9XAAAAAAADpuUAFjBHU3MwR1YzNEtYN0tDcEx3OXRXamsAAQA1aHR0cHM6Ly9vcGVuLnNwb3RpZnkuY29tL3RyYWNrLzBHU3MwR1YzNEtYN0tDcEx3OXRXamsAB3Nwb3RpZnkBAAxKUEtTMDA0MDA0MjEBAEBodHRwczovL2kuc2Nkbi5jby9pbWFnZS9hYjY3NjE2ZDAwMDBiMjczYTcyMmRiMGM2YTgwNDQ2NzQ0NjBlNmE0AAAAAAAAAAA=","position":10.04052734375}
2022-11-13 20:55:26.582 ERROR 75000 --- [XNIO-1 task-1] io.undertow.request                      : UT005023: Exception handling request to /v3/sessions/p1vwf8ltrm9ngu3y/players/133049272517001216

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException: audioPlayerManager.decod…Input(bais)).decodedTrack must not be null
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:880) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[jakarta.servlet-api-4.0.4.jar!/:4.0.4]
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at org.springframework.web.filter.AbstractRequestLoggingFilter.doFilterInternal(AbstractRequestLoggingFilter.java:289) ~[spring-web-5.3.18.jar!/:5.3.18]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar!/:5.3.18]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at lavalink.server.io.ResponseHeaderFilter.doFilterInternal(ResponseHeaderFilter.kt:17) ~[classes!/:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar!/:5.3.18]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.18.jar!/:5.3.18]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar!/:5.3.18]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) ~[jboss-threads-3.1.0.Final.jar!/:3.1.0.Final]
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) ~[jboss-threads-3.1.0.Final.jar!/:3.1.0.Final]
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) ~[jboss-threads-3.1.0.F [...]

2022-11-21 12:50 UTC, Devoxin requested changes

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/config/AudioSourcesConfig.kt
> +    var isYoutube: Boolean = true,
These could probably all be `val`?

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/config/HttpConfig.kt
> +    var proxyHost: String = "",
As above -- could be `val`?

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/config/MetricsPrometheusConfigProperties.kt
> +    var isEnabled: Boolean = false,
As above -- could be `val`?

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/config/RateLimitConfig.kt
> +    var ipBlocks: List<String> = emptyList(),
As above -- could be `val`?

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/config/RequestAuthorizationFilter.kt
> +                        log.warn("Authorization missing for ${request.remoteAddr} on ${request.method} $path")
This could probably be `log.warn("... {} on {}", request.remoteAddr, ...)` for consistency.

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/config/RequestAuthorizationFilter.kt
> +                    log.warn("Authorization failed for ${request.remoteAddr} on ${request.method} $path")
As above regarding log format consistency.

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/config/RequestLoggingConfig.kt
> +    var includeClientInfo: Boolean = true,
As above -- could be `val`?

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/config/SentryConfiguration.kt
> +            log.info("Setting sentry release to commit hash $commitHash")
As above regarding log format consistency.

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/config/ServerConfig.kt
>      var password: String? = null
As above -- could be `val`?

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/config/YoutubeConfig.kt
> +    var email: String = "",
As above -- could be `val`?

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/info/AppInfo.kt
> +        buildTime = try {
```suggestion
buildTime = prop.getProperty("buildTime").toLongOrNull() ?: -1
```

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/info/GitRepoState.kt
> +    final var commitTime: Long = 0
Could be val, with `= 0` removed as it's set below regardless?

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/io/HandshakeInterceptorImpl.kt
> +        log.info("Incoming connection from " + request.remoteAddress)
As above regarding log format consistency.

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/io/HandshakeInterceptorImpl.kt
> +            log.error("Missing User-Id header from " + request.remoteAddress)
As above regarding log format consistency.

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/io/HandshakeInterceptorImpl.kt
>              log.error("Authentication failed from " + request.remoteAddress)
As above regarding log format consistency.

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/io/HandshakeInterceptorImpl.kt
> +        response.headers.add("Lavalink-Api-Version", "3")
Is this necessary with the `ResponseHeaderFilter`?

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/io/RoutePlannerRestHandler.kt
> +        ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR, "Can't access disabled route planner")
Perhaps this should be `BAD_REQUEST`?

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/io/SocketContext.kt
>              players.values.forEach { player -> if (player.isPlaying) newList.add(player) }
Could this just be `return players.values.filter { it.isPlaying }`?

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/io/SocketServer.kt
> +                    "Shutdown resumable session with key ${removed.resumeKey} because it has the same key as a " +
As above regarding log format consistency.

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/io/WebSocketHandler.kt
> +                        "'filters' op. Please switch to use that one, as this op will get removed in v4."
```suggestion
                        "'filters' op. Please switch to that one, as this op will be removed in v4."
```

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/player/AudioLoader.kt
> +        log.trace("Loading item with identifier {}", identifier)
Trace seems a little too granular. Maybe debug would be better?

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/player/AudioLoader.kt
> +        log.info("Loaded track " + audioTrack.info.title)
As above regarding log format consistency.

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/player/AudioLoader.kt
> +        log.info("Loaded playlist " + audioPlaylist.name)
As above regarding log format consistency.

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/player/AudioLoader.kt
> +        loadResult.complete(LoadResult(Exception(e)))
Is wrapping an exception necessary? Could we just return `e` here?

2022-11-21 12:50 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/player/EventEmitter.kt
> +        log.warn(track.info.title + " got stuck! Threshold surpassed: " + thresholdMs)
As above regarding log format consistency.

2022-11-21 12:50 UTC, Devoxin commented on protocol/src/main/java/dev/arbjerg/lavalink/protocol/filters.kt
> +    var volume: Float? = null,
Any reason for volume being `var`?

2022-11-21 12:50 UTC, Devoxin commented on protocol/src/main/java/dev/arbjerg/lavalink/protocol/filters.kt
> +    var equalizer: List<Band>? = null,
As above.

2022-11-21 12:50 UTC, Devoxin commented on protocol/src/main/java/dev/arbjerg/lavalink/protocol/loadResult.kt
> +    var loadType: ResultStatus, var tracks: List<Track>, var playlistInfo: PlaylistInfo?, var exception: Exception?
These could be on separate lines, and potentially moved to `val`.

2022-11-21 12:50 UTC, Devoxin commented on protocol/src/main/java/dev/arbjerg/lavalink/protocol/loadResult.kt
> +    val name: String, val selectedTrack: Int
new line

2022-11-21 12:50 UTC, Devoxin commented on protocol/src/main/java/dev/arbjerg/lavalink/protocol/loadResult.kt
> +    val message: String?, val severity: FriendlyException.Severity, val cause: String
new line

2022-11-21 12:50 UTC, Devoxin commented on protocol/src/main/java/dev/arbjerg/lavalink/protocol/loadResult.kt
> +    TRACK_LOADED, PLAYLIST_LOADED, SEARCH_RESULT, NO_MATCHES, LOAD_FAILED
new line

2022-11-21 12:50 UTC, Devoxin commented on protocol/src/main/java/dev/arbjerg/lavalink/protocol/messages.kt
> +sealed class Message(var op: Op) {
Could be val?

2022-11-21 12:50 UTC, Devoxin commented on protocol/src/main/java/dev/arbjerg/lavalink/protocol/session.kt
> +    var resumingKey: Omissible<String?> = Omissible.omitted(),
`val`?

2022-11-21 12:50 UTC, Devoxin commented on protocol/src/main/java/dev/arbjerg/lavalink/protocol/session.kt
> +    var timeout: Omissible<Long> = Omissible.omitted(),
As above.

2022-11-22 09:26 UTC, TopiSenpai commented on LavalinkServer/src/main/java/lavalink/server/io/RoutePlannerRestHandler.kt
> +        ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR, "Can't access disabled route planner")
this would be a breaking change

2022-11-22 09:28 UTC, TopiSenpai commented on LavalinkServer/src/main/java/lavalink/server/io/SocketContext.kt
>              players.values.forEach { player -> if (player.isPlaying) newList.add(player) }
does filter return a new list?

2022-11-22 09:44 UTC, TopiSenpai commented on LavalinkServer/src/main/java/lavalink/server/player/AudioLoader.kt
> +        log.trace("Loading item with identifier {}", identifier)
this has always been trace so I'll keep it this way

2022-11-22 09:45 UTC, TopiSenpai commented on LavalinkServer/src/main/java/lavalink/server/player/AudioLoader.kt
> +        loadResult.complete(LoadResult(Exception(e)))
this is the data class `Exception` for marshalling

2022-11-25 18:49 UTC, Drapersniper commented
Documentation for [64632e6](https://github.com/freyacodes/Lavalink/pull/748/commits/64632e6d14ad5bc61ff5529c87e1f3f3ac59c875) is missing unless I'm blind.

2022-11-25 18:51 UTC, TopiSenpai commented
> Documentation for [64632e6](https://github.com/freyacodes/Lavalink/pull/748/commits/64632e6d14ad5bc61ff5529c87e1f3f3ac59c875) is missing unless I'm blind.

should be there: https://github.com/freyacodes/Lavalink/blob/feature/rest-api/IMPLEMENTATION.md#get-lavalink-info

2022-11-27 13:17 UTC, freyacodes commented
A lot of this pull request is the conversion of Java to Kotlin. It would have been easier to review if those conversions had been committed to v3.7 and then merged back here

2022-11-27 14:03 UTC, freyacodes requested changes
This is a partial review of everything but the protocol module. I'll get back to that later

2022-11-27 14:03 UTC, freyacodes commented on LavalinkServer/application.yml.example
> +    filters: # All filters are enabled by default
Should have instead merged dev into v3.7 first. Those changes now get mixed in with the changes of this PR

2022-11-27 14:03 UTC, freyacodes commented on LavalinkServer/application.yml.example
> +  request:
Should probably be moved to `lavalink.server`

2022-11-27 14:03 UTC, freyacodes commented on LavalinkServer/src/main/java/lavalink/server/Launcher.kt
> +        }
Nice. I like this

2022-11-27 14:03 UTC, freyacodes commented on LavalinkServer/src/main/java/lavalink/server/config/HttpConfig.kt
> +    var proxyHost: String = "",
I believe the getters are used by Spring Boot, but I am not sure

2022-11-27 14:03 UTC, freyacodes commented on LavalinkServer/src/main/java/lavalink/server/io/WebSocketHandler.kt
> +            log.warn("Sending websocket commands to Lavalink has been deprecated and will be removed in v4. Please use the new REST endpoints instead.")
```suggestion
            log.warn("Sending websocket commands to Lavalink has been deprecated and will be removed in API version 4. API version 3 will be removed in Lavalink 5. Please use the new REST endpoints instead.")
```

2022-11-27 14:03 UTC, freyacodes commented on LavalinkServer/src/main/java/lavalink/server/io/WebSocketHandler.kt
> +                        "'filters' op. Please switch to that one, as this op will be removed in v4."
```suggestion
                        "'filters' op. Please switch to that one, as this op will be removed in API version 4."
```

2022-11-27 14:03 UTC, freyacodes commented on LavalinkServer/src/main/java/lavalink/server/io/WebSocketHandler.kt
> +            log.warn("Following filters are disabled in the config, ignoring filters op: $invalidFilters")
```suggestion
            log.warn("The following filters are disabled in the config and are being ignored: $invalidFilters")
```

2022-11-27 14:03 UTC, freyacodes commented on LavalinkServer/src/main/java/lavalink/server/player/PlayerRestHandler.kt
> +    @GetMapping(value = ["/v3/sessions/{sessionId}/players"], produces = ["application/json"])
Could probably return the Content-Type for all requests as we always return JSON

2022-11-27 14:03 UTC, freyacodes commented on LavalinkServer/src/main/java/lavalink/server/player/PlayerRestHandler.kt
> +                throw ResponseStatusException(HttpStatus.BAD_REQUEST, "Partial voice state update")
```suggestion
                throw ResponseStatusException(HttpStatus.BAD_REQUEST, "Partial voice state update: $it")
```

2022-11-27 14:03 UTC, freyacodes commented on plugin-api/src/main/java/dev/arbjerg/lavalink/api/AudioFilterExtension.java
> +    default FloatPcmAudioFilter build(JSONObject data, AudioDataFormat format, FloatPcmAudioFilter output) {
Add `@Deprecated` annotations to all deprecated functions

2022-11-27 14:03 UTC, freyacodes commented on plugin-api/src/main/java/dev/arbjerg/lavalink/api/ISocketContext.java
>      void sendMessage(JSONObject message);
Add Deprecated header

2022-11-27 14:17 UTC, TopiSenpai commented on LavalinkServer/src/main/java/lavalink/server/config/HttpConfig.kt
> +    var proxyHost: String = "",
I tested it with `val` and it didn't work. Got an error along the lines of no setter found

2022-11-27 14:18 UTC, TopiSenpai commented on LavalinkServer/application.yml.example
> +    filters: # All filters are enabled by default
urgh seems like I forgot that
annoying

2022-11-27 14:18 UTC, TopiSenpai commented on LavalinkServer/application.yml.example
> +  request:
I put it here as it's also part of the logging but if you prefer that sure

2022-11-27 14:19 UTC, TopiSenpai commented on LavalinkServer/src/main/java/lavalink/server/player/PlayerRestHandler.kt
> +    @GetMapping(value = ["/v3/sessions/{sessionId}/players"], produces = ["application/json"])
there is one exception on the `/version` endpoint

2022-11-27 14:27 UTC, freyacodes commented on LavalinkServer/src/main/java/lavalink/server/player/PlayerRestHandler.kt
> +    @GetMapping(value = ["/v3/sessions/{sessionId}/players"], produces = ["application/json"])
Then we can have a filter that sets content-type, with `/version` exceptionally being `text/plain`

2022-11-27 14:28 UTC, freyacodes commented on LavalinkServer/application.yml.example
> +  request:
Ah nevermind. `lavalink.logging` is a good place. I thought it was at `lavalink`

2022-11-27 14:29 UTC, TopiSenpai commented on LavalinkServer/application.yml.example
> +  request:
it's `logging.request` atm

2022-11-27 14:35 UTC, TopiSenpai commented on LavalinkServer/src/main/java/lavalink/server/player/PlayerRestHandler.kt
> +    @GetMapping(value = ["/v3/sessions/{sessionId}/players"], produces = ["application/json"])
it seems like spring adds the content-type automatically. so there is no need to even explicitly set it

2022-11-27 15:04 UTC, freyacodes commented on LavalinkServer/application.yml.example
> +  request:
Yeah that's good

2022-11-27 15:06 UTC, freyacodes commented
Do we have a working client for the REST API?

2022-11-27 15:23 UTC, TopiSenpai commented
> Do we have a working client for the REST API?

Not a java one
I built some go stuff & there is some python stuff from @Drapersniper 
There is postman/insomnia collection

2022-11-27 15:38 UTC, parasop commented
> > Do we have a working client for the REST API?
> 
> Not a java one I built some go stuff & there is some python stuff from @Drapersniper There is postman/insomnia collection

I will made  rest client in nodejs 
https://github.com/parasop/poru

2023-01-14 19:55 UTC, freyacodes requested changes

2023-01-14 19:55 UTC, freyacodes commented on protocol/build.gradle.kts
> +                url.set("https://github.com/freyacodes/lavalink")
This is not the plugin API

2023-01-14 19:55 UTC, freyacodes commented on protocol/src/main/java/dev/arbjerg/lavalink/protocol/v3/plugin.kt
> +data class Plugin(val name: String, val version: String)
Looks like this is only used in `info.kt`, so maybe move it there?

2023-01-14 19:55 UTC, freyacodes commented on protocol/src/main/java/dev/arbjerg/lavalink/protocol/v3/stats.kt
> +    val deficit: Long
```suggestion
    val sent: Int,
    val nulled: Int,
    val deficit: Int
```

2023-01-14 20:16 UTC, freyacodes approved these changes

2023-01-14 20:26 UTC, merged