proposed api changes for v3.6
lavalink-devs/Lavalink pull request #750
Opened 2022-09-20 18:11 UTC by TopiSenpai

2022-09-20 18:51 UTC, TopiSenpai commented
This is a proposal and you're actively encouraged to give input/feedback.

If you disagree with any of the mentioned changes let us know so we can discuss them.
If you want any features which are in the scope of this pr let us also know

2022-09-20 19:04 UTC, Devoxin commented on IMPLEMENTATION.md
> +      "ping": 10 // -1 if not connected
Should probably specify this is in milliseconds

2022-09-20 19:04 UTC, Devoxin commented on IMPLEMENTATION.md
> +    "ping": 10 // -1 if not connected
Same again here (specify ms)

2022-09-20 19:05 UTC, Devoxin commented on IMPLEMENTATION.md
> +You can provide eiter `trackData` or `identifier` or nothing, not both.
either

2022-09-20 23:24 UTC, Devoxin commented on IMPLEMENTATION.md
> +* Add of new incoming message [Ready OP](#ready-op) to get `sessionId` and `resume` status.
```suggestion
* Addition of new WebSocket dispatch [Ready OP](#ready-op) to get `sessionId` and `resume` status.
```

2022-09-20 23:24 UTC, Devoxin commented on IMPLEMENTATION.md
> +* Deprecation of all outgoing messages(play, stop, pause, seek, volume, filters, destroy, voiceUpdate & configureResuming).
```suggestion
* Deprecation of all outgoing messages (play, stop, pause, seek, volume, filters, destroy, voiceUpdate & configureResuming).
```

2022-09-20 23:24 UTC, Devoxin commented on IMPLEMENTATION.md
> +Tells you if you resumed successfully and your sessionId used for REST requests.
```suggestion
Dispatched by Lavalink upon successful connection and authorization. Contains fields determining if resuming was successful, as well as the session ID.
```

2022-09-20 23:24 UTC, Devoxin commented on IMPLEMENTATION.md
> +### Incoming messages
This should perhaps be a header encompassing the aforementioned op messages to better distinguish between implementation sections.

2022-09-20 23:24 UTC, Devoxin commented on IMPLEMENTATION.md
> +Authorization: youshallnotpass
It may be worth removing this and instead detailing that such endpoints require an "Authorization" header containing the password specified in the application.yml, just to prevent any confusion in case folks take this a little too literally.

2022-09-20 23:24 UTC, Devoxin commented on IMPLEMENTATION.md
> +Authorization: youshallnotpass
Same again here.

2022-09-20 23:24 UTC, Devoxin commented on IMPLEMENTATION.md
> +Authorization: youshallnotpass
See above.

2022-09-20 23:24 UTC, Devoxin commented on IMPLEMENTATION.md
> +Authorization: youshallnotpass
See above.

2022-09-20 23:24 UTC, Devoxin commented on IMPLEMENTATION.md
>  Authorization: youshallnotpass
See above.

2022-09-20 23:24 UTC, Devoxin commented on IMPLEMENTATION.md
> +204 - No Content
Perhaps 404 should be returned where a player doesn't exist?

2022-09-20 23:24 UTC, Devoxin commented on IMPLEMENTATION.md
> +Authorization: youshallnotpass
See above.

2022-09-20 23:24 UTC, Devoxin commented on IMPLEMENTATION.md
> +204 - No Content
404 here as well if sessionId not found?

2022-09-20 23:24 UTC, Devoxin commented on IMPLEMENTATION.md
>  Decode multiple tracks into info their info
This reads weirdly.

2022-09-20 23:24 UTC, Devoxin commented on IMPLEMENTATION.md
>  Authorization: youshallnotpass
See above.

2022-09-20 23:24 UTC, Devoxin commented on IMPLEMENTATION.md
> +The REST api is used to resolve audio tracks for use with the `play` op.
is `play` op the correct terminology or is `play` endpoint meant instead?

2022-09-20 23:24 UTC, Devoxin commented on IMPLEMENTATION.md
>  Authorization: youshallnotpass
See above.

2022-09-20 23:24 UTC, Devoxin commented on IMPLEMENTATION.md
> +Authorization: youshallnotpass
See above.

2022-09-20 23:24 UTC, Devoxin commented on IMPLEMENTATION.md
>  Authorization: youshallnotpass
See above.

2022-09-20 23:24 UTC, Devoxin commented on IMPLEMENTATION.md
>  Authorization: youshallnotpass
See above.

2022-09-20 23:24 UTC, Devoxin commented on IMPLEMENTATION.md
>  Authorization: youshallnotpass
See above.

2022-09-20 23:51 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +The REST api is used to resolve audio tracks for use with the `play` op.
it refers to the "old" ws ops which it shouldn't

2022-09-26 22:39 UTC, TopiSenpai commented
I added a new `/info` endpoint which will replace the current `/version` endpoint
this endpoint adds additional info about the node including:
- lavalink version
- build time
- git branch
- git commit hash
- git commit time
- java version
- lavaplayer version
- active audio sources

if you feel like this is missing something or you would prefer a different json structure let me know

2022-09-27 09:33 UTC, Tomato6966 commented
maybe OS & Distrobution

2022-09-27 12:12 UTC, topi314 commented
> Distrobution

what do you mean by that?

2022-09-27 12:13 UTC, Devoxin commented
Distribution*, such as debian, Ubuntu, etc.

Seems useless information, though

2022-09-27 12:18 UTC, TopiSenpai commented
I also think it's not relevant
arguably the jvm version also isn't

2022-09-27 14:24 UTC, freyacodes reviewed
Use `yaml` as the language for JSON code blocks with comments to avoid syntax warnings. YAML is a JSON superset (believe it or not) that supports comments

Perhaps we should use markdown tables instead of JSON code blocks for API entities? Similar to what Discord does for their developer documentation,

The meaning of the different properties should be documented, and this is currently not the case. Doing so would be easier if we didn't have to use inline comments.

2022-09-27 14:24 UTC, freyacodes commented on IMPLEMENTATION.md
> +* Deprecation of all outgoing messages (play, stop, pause, seek, volume, filters, destroy, voiceUpdate & configureResuming).
```suggestion
* Deprecation of all client messages (play, stop, pause, seek, volume, filters, destroy, voiceUpdate & configureResuming).
```

2022-09-27 14:24 UTC, freyacodes commented on IMPLEMENTATION.md
> +204 - No Content
Yes, but that should not be documented here as it would apply to all endpoints with that path variable

2022-10-05 14:08 UTC, TopiSenpai commented
I updated the docs with markdown tables for all non deprecated things except route planner api(this will come later)

if anyone has some feedback on the formatting feel free to tell me.
You can see the file as a whole [here](https://github.com/freyacodes/Lavalink/blob/new-api-draft/IMPLEMENTATION.md)

2022-10-05 23:06 UTC, aikaterna requested changes

2022-10-05 23:06 UTC, aikaterna commented on IMPLEMENTATION.md
> +| filterWidth? | float | The filter width(0.1 to 1.0 where 0.1 is narrow and 1.0 is wide)       |
```suggestion
| level?       | float | The level (0 to 1.0 where 0.0 is no effect and 1.0 is full effect)      |
| monoLevel?   | float | The mono level (0 to 1.0 where 0.0 is no effect and 1.0 is full effect) |
| filterBand?  | float | The filter band (1.0 to 15.0)                                               |
| filterWidth? | float | The filter width (0.1 to 1.0 where 0.1 is narrow and 1.0 is wide)       |
```

2022-10-05 23:06 UTC, aikaterna commented on IMPLEMENTATION.md
> +> `/version` is deprecated and for removal in v4 use [`/info`](#get-lavalink-info) instead
```suggestion
> `/version` is deprecated and marked for removal in v4, use [`/info`](#get-lavalink-info) instead
```

2022-10-05 23:06 UTC, aikaterna commented on IMPLEMENTATION.md
> +> `/plugins` is deprecated and for removal in v4
```suggestion
> `/plugins` is deprecated and marked for removal in v4
```

2022-10-05 23:06 UTC, aikaterna commented on IMPLEMENTATION.md
> +| builtTime      | int                                | The time this Lavalink jar was built               |
```suggestion
| builtTime      | int                                | The Unix timestamp of when this Lavalink jar was built               |
```
Should this also specify whether the int is ms or seconds? Not sure which value type is returned currently.

2022-10-05 23:06 UTC, aikaterna commented on IMPLEMENTATION.md
> +> `/loadtracks?identifier=dQw4w9WgXcQ` is deprecated and for removal in v4
```suggestion
> `/loadtracks?identifier=dQw4w9WgXcQ` is deprecated and marked for removal in v4
```

2022-10-05 23:06 UTC, aikaterna commented on IMPLEMENTATION.md
> +> `/decodetrack?track=QAAAjJ...AAA==` is deprecated and for removal in v4
```suggestion
> `/decodetrack?track=QAAAjJ...AAA==` is deprecated and marked for removal in v4
```

2022-10-05 23:06 UTC, aikaterna commented on IMPLEMENTATION.md
> +> `/decodetracks` is deprecated and for removal in v4
```suggestion
> `/decodetracks` is deprecated and marked for removal in v4
```

2022-10-05 23:06 UTC, aikaterna commented on IMPLEMENTATION.md
> +> `/routeplanner/status` is deprecated and for removal in v4
```suggestion
> `/routeplanner/status` is deprecated and marked for removal in v4
```

2022-10-05 23:06 UTC, aikaterna commented on IMPLEMENTATION.md
> +> `/routeplanner/free/address` is deprecated and for removal in v4
```suggestion
> `/routeplanner/free/address` is deprecated and marked for removal in v4
```

2022-10-05 23:06 UTC, aikaterna commented on IMPLEMENTATION.md
> +> `/routeplanner/free/all` is deprecated and for removal in v4
```suggestion
> `/routeplanner/free/all` is deprecated and marked for removal in v4
```

2022-10-05 23:06 UTC, aikaterna commented on IMPLEMENTATION.md
> +| selectedTrack | int    | The selected track in this Playlist(-1 if no track is selected) |
```suggestion
| selectedTrack | int    | The selected track in this Playlist (-1 if no track is selected) |
```

2022-10-05 23:06 UTC, aikaterna commented on IMPLEMENTATION.md
> +| gain  | float | The gain(-0.25 to 1.0) |
```suggestion
| bands | int   | The band (0 to 14)      |
| gain  | float | The gain (-0.25 to 1.0) |
```

2022-10-05 23:06 UTC, aikaterna commented on IMPLEMENTATION.md
> +| lowPass?    | [Low Pass](#low-pass)object        | Lets you filter higher frequencies                                                                |
```suggestion
| lowPass?    | [Low Pass](#low-pass) object        | Lets you filter higher frequencies                                                                |
```

2022-10-05 23:13 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +| builtTime      | int                                | The time this Lavalink jar was built               |
sure this is in milliseconds

2022-10-12 14:36 UTC, freyacodes commented
Is there anything else that needs to be changed?

2022-10-12 15:09 UTC, freyacodes requested changes
I've quickly skimmed through this and it mostly looks good

2022-10-12 15:09 UTC, freyacodes commented on IMPLEMENTATION.md
> +* Deprecation of [track decoding response](#track-decoding).
It's not deprecated though?

2022-10-12 15:09 UTC, freyacodes commented on IMPLEMENTATION.md
> +One problem we noticed is that since JD-AA is unaware of ratelimits on the bots gateway connection, it would keep adding
JD-AA?

2022-10-12 19:00 UTC, ooliver1 requested changes

2022-10-12 19:00 UTC, ooliver1 commented on IMPLEMENTATION.md
> +| FINISH      | The track finished playing | true           |
`FINISH` seems to be in a different tense compared to `*ED`, it also does not match the example.

2022-10-12 19:00 UTC, ooliver1 commented on IMPLEMENTATION.md
> +Returns a list players in this specific session.
```suggestion
Returns a list of players in this specific session.
```

2022-10-12 19:00 UTC, ooliver1 commented on IMPLEMENTATION.md
> +| volume  | int                                | The volume of the player, range 0-150, in percentage |
Previously, the max volume was 500, has that changed?

2022-10-12 19:00 UTC, ooliver1 commented on IMPLEMENTATION.md
> +| ping      | ?int   | Roundtrip latency to the voice gateway. Response only |
Could this mention the units? i.e. `ms`

2022-10-12 19:00 UTC, ooliver1 commented on IMPLEMENTATION.md
> +```yaml
```suggestion
```json
```
non-standard github clients may see the `yaml` language type and get confused.

2022-10-12 19:00 UTC, ooliver1 commented on IMPLEMENTATION.md
> +> `/plugins` is deprecated and marked for removal in v4
Perhaps mention `/v$/info/` supersedes this, like in `Get Lavalink version`

2022-10-12 19:00 UTC, ooliver1 commented on IMPLEMENTATION.md
> +| voiceSession? | [Voice State](#voice-state) object | Information required for connecting to Discord, without `connected` or `ping` |
This does not seem to match the example:
`voiceSession?`
`sessionId`
`event`

2022-10-12 19:20 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +| volume  | int                                | The volume of the player, range 0-150, in percentage |
this is actually capped by lavaplayer at 1000 https://github.com/Walkyst/lavaplayer-fork/blob/original/main/src/main/java/com/sedmelluq/discord/lavaplayer/player/DefaultAudioPlayer.java#L290 and not currently capped by lavalink at all

2022-10-12 19:22 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +```yaml
we use yaml here because of comments. see: https://github.com/freyacodes/Lavalink/pull/750#pullrequestreview-1122080700

2022-10-12 20:01 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +| `RotatingNanoIpRoutePlanner` | ...         |
Those 3 fields need a description but I have no idea

2022-10-13 00:47 UTC, aikaterna commented on IMPLEMENTATION.md
> +| volume  | int                                | The volume of the player, range 0-1000, in percentage |
Should this still say "percentage" when it's properly listed at 1-1000 now?

2022-10-13 00:47 UTC, aikaterna commented on IMPLEMENTATION.md
> +* Addition of REST endpoints intended to replace client requests
```suggestion
* Addition of REST endpoints intended to replace client requests.
```

2022-10-13 00:47 UTC, aikaterna commented on IMPLEMENTATION.md
>  User-Id: The user id of the bot you are playing music with
```suggestion
User-Id: The user id of the bot you are playing music with, in string format
```
Not sure if you want this change since this line is not being touched in this PR, but it may be good to let people know to not send an int

2022-10-13 00:47 UTC, aikaterna commented on IMPLEMENTATION.md
> +| [playerUpdate](#player-update-op) | Emitted when every x seconds with the latest player state    |
```suggestion
| [playerUpdate](#player-update-op) | Emitted every x seconds with the latest player state         |
```

2022-10-13 00:47 UTC, aikaterna commented on IMPLEMENTATION.md
> +| [ready](#ready-op)                | Emitted when you successfully connected to the Lavalink node |
```suggestion
| [ready](#ready-op)                | Emitted when you successfully connect to the Lavalink node   |
```

2022-10-13 00:47 UTC, aikaterna commented on IMPLEMENTATION.md
> +Dispatched every x(configurable in `application.yml`) seconds with the current state of the player.
```suggestion
Dispatched every x (configurable in `application.yml`) seconds with the current state of the player.
```

2022-10-13 00:47 UTC, aikaterna commented on IMPLEMENTATION.md
> +| track   | string | The track that started playing           |
Should there be a description here for the track that indicates it's one of the b64 strings?

2022-10-13 00:47 UTC, aikaterna commented on IMPLEMENTATION.md
> +| code     | int    | The [discord close event code](https://discord.com/developers/docs/topics/opcodes-and-status-codes#voice-voice-close-event-codes) |
```suggestion
| code     | int    | The [Discord close event code](https://discord.com/developers/docs/topics/opcodes-and-status-codes#voice-voice-close-event-codes) |
```

2022-10-13 00:47 UTC, aikaterna commented on IMPLEMENTATION.md
> +| volume?       | int                                | The volume from 0 to 200                                                      |
Is 0 -> 200 correct?

2022-10-13 00:47 UTC, aikaterna commented on IMPLEMENTATION.md
> +Changes the speed, pitch, and rate. All default to 1.
```suggestion
Changes the speed, pitch, and rate. All default to 1.0.
```

2022-10-13 00:47 UTC, aikaterna commented on IMPLEMENTATION.md
>  Additionally, there are a few REST endpoints for the ip rotation extension
```suggestion
Additionally, there are a few REST endpoints for the ip rotation extension.
```

2022-10-13 00:47 UTC, aikaterna commented on IMPLEMENTATION.md
> +| `RotatingNanoIpRoutePlanner` | ...         |
```suggestion
| Route Planner Type           | Description                                                                                                                  |
|------------------------------|------------------------------------------------------------------------------------------------------------------------------|
| `RotatingIpRoutePlanner`     | IP address used is switched on ban. Recommended for IPv4 blocks or IPv6 blocks smaller than a /64.                            |
| `NanoIpRoutePlanner`         | IP address used is switched on clock update. Use with at least 1 /64 IPv6 block.                                             |
| `RotatingNanoIpRoutePlanner` | IP address used is switched on clock update, rotates to a different /64 block on ban. Use with at least 2x /64 IPv6 blocks.  |
```

2022-10-13 00:47 UTC, aikaterna commented on IMPLEMENTATION.md
> +To enable resuming, you must call the [Update Session](#update-session) endpoint with the `resumingKey` and `timeout`
```suggestion
To enable resuming, you must call the [Update Session](#update-session) endpoint with the `resumingKey` and `timeout`.
```

2022-10-13 00:47 UTC, aikaterna commented on IMPLEMENTATION.md
>  * When your shard's main WS connection dies, so does all your lavalink audio connections.
```suggestion
* When your shard's main WS connection dies, so does all your Lavalink audio connections.
```

2022-10-13 00:50 UTC, TopiSenpai commented on IMPLEMENTATION.md
>  User-Id: The user id of the bot you are playing music with
headers are always strings so this is not needed

2022-10-13 01:08 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +| volume  | int                                | The volume of the player, range 0-1000, in percentage |
0 = 0%, 1000 = 1000% so yes this should stay

2022-10-17 10:15 UTC, Drapersniper reviewed
Noticed that we are refering to the b64 encoded data in a few different ways, it would be great if we could have some consistance here just so that it makes it a little more intutive when it comes time to develop for and use v3.7+

2022-10-17 10:15 UTC, Drapersniper commented on IMPLEMENTATION.md
> +| encodedTrack? | ?string                            | The encoded track data to play. `null` stops the current track                |
Could we please keep the names consistent? It would make developing libraries for it much more intuitive. 
The B64 is currently refered to in different ways (`track`, `trackData`, `encoded` and `encodedTrack`)  

Given the context where these show up in `encodedTrack` is probably the best choice here which can be used in all these places without ambiguity.

2022-10-17 10:15 UTC, Drapersniper commented on IMPLEMENTATION.md
> +    "encoded": "QAAAjQIAJVJpY2sgQXN0bGV5IC0gTmV2ZXIgR29ubmEgR2l2ZSBZb3UgVXAADlJpY2tBc3RsZXlWRVZPAAAAAAADPCAAC2RRdzR3OVdnWGNRAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9ZFF3NHc5V2dYY1EAB3lvdXR1YmU
Same as my previous comment

2022-10-17 10:15 UTC, Drapersniper commented on IMPLEMENTATION.md
> +  "encoded": "QAAAjQIAJVJpY2sgQXN0bGV5IC0gTmV2ZXIgR29ubmEgR2l2ZSBZb3UgVXAADlJpY2tBc3RsZXlWRVZPAAAAAAADPCAAC2RRdzR3OVdnWGNRAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9ZFF3NHc5V2dYY1EAB3lvdXR1YmUAA
Same as my previous comment

2022-10-17 10:15 UTC, Drapersniper commented on IMPLEMENTATION.md
> +    "encoded": "QAAAjQIAJVJpY2sgQXN0bGV5IC0gTmV2ZXIgR29ubmEgR2l2ZSBZb3UgVXAADlJpY2tBc3RsZXlWRVZPAAAAAAADPCAAC2RRdzR3OVdnWGNRAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9ZFF3NHc5V2dYY1EAB3lvdXR1YmU
Same as my previous comment

2022-10-17 10:15 UTC, Drapersniper commented on IMPLEMENTATION.md
> +      "encoded": "QAAAjQIAJVJpY2sgQXN0bGV5IC0gTmV2ZXIgR29ubmEgR2l2ZSBZb3UgVXAADlJpY2tBc3RsZXlWRVZPAAAAAAADPCAAC2RRdzR3OVdnWGNRAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9ZFF3NHc5V2dYY1EAB3lvdXR1Y
Same as my previous comment

2022-10-17 10:15 UTC, Drapersniper commented on IMPLEMENTATION.md
> +      "encoded": "QAAAjQIAJVJpY2sgQXN0bGV5IC0gTmV2ZXIgR29ubmEgR2l2ZSBZb3UgVXAADlJpY2tBc3RsZXlWRVZPAAAAAAADPCAAC2RRdzR3OVdnWGNRAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9ZFF3NHc5V2dYY1EAB3lvdXR1Y
Same as my previous comment

2022-10-17 10:15 UTC, Drapersniper commented on IMPLEMENTATION.md
> +  "sourceManagers": [
Are these the same as the `sourceName` returned in the TrackObject ?

2022-10-17 10:15 UTC, Drapersniper commented on IMPLEMENTATION.md
> +      "trackData": "QAAAjQIAJVJpY2sgQXN0bGV5IC0gTmV2ZXIgR29ubmEgR2l2ZSBZb3UgVXAADlJpY2tBc3RsZXlWRVZPAAAAAAADPCAAC2RRdzR3OVdnWGNRAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9ZFF3NHc5V2dYY1EAB3lvdXR
Same as my previous comment

2022-10-17 10:15 UTC, Drapersniper commented on IMPLEMENTATION.md
> +    "trackData": "QAAAjQIAJVJpY2sgQXN0bGV5IC0gTmV2ZXIgR29ubmEgR2l2ZSBZb3UgVXAADlJpY2tBc3RsZXlWRVZPAAAAAAADPCAAC2RRdzR3OVdnWGNRAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9ZFF3NHc5V2dYY1EAB3lvdXR1Y
Same as my previous comment

2022-10-17 10:15 UTC, Drapersniper commented on IMPLEMENTATION.md
> +  "encodedTrack": "...",
Same as my previous comment

2022-10-17 10:15 UTC, Drapersniper commented on IMPLEMENTATION.md
> +Note that `encodedTrack` and `identifier` are mutually exclusive.
Same as my previous comment

2022-10-17 10:15 UTC, Drapersniper commented on IMPLEMENTATION.md
> +| encoded | string                           | The base64 encoded track data                                                 |
Same as my previous comment

2022-10-17 10:15 UTC, Drapersniper commented on IMPLEMENTATION.md
> +| track     | string                                | The encoded track that threw the exception |
Could we please keep the names consistent? It would make developing libraries for it much more intuitive. 
The B64 is currently refered to in different ways (`track`, `trackData`, `encoded` and `encodedTrack`)

2022-10-17 11:27 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +  "sourceManagers": [
they are

2022-10-17 11:30 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +      "trackData": "QAAAjQIAJVJpY2sgQXN0bGV5IC0gTmV2ZXIgR29ubmEgR2l2ZSBZb3UgVXAADlJpY2tBc3RsZXlWRVZPAAAAAAADPCAAC2RRdzR3OVdnWGNRAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9ZFF3NHc5V2dYY1EAB3lvdXR
this is an oversight & should be updated

2022-10-17 11:30 UTC, topi314 commented on IMPLEMENTATION.md
> +    "trackData": "QAAAjQIAJVJpY2sgQXN0bGV5IC0gTmV2ZXIgR29ubmEgR2l2ZSBZb3UgVXAADlJpY2tBc3RsZXlWRVZPAAAAAAADPCAAC2RRdzR3OVdnWGNRAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9ZFF3NHc5V2dYY1EAB3lvdXR1Y
this is an oversight & should be updated

2022-10-17 11:34 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +| encodedTrack? | ?string                            | The encoded track data to play. `null` stops the current track                |
`trackData` should be removed in all cases this is just an oversight in the examples
`track` refers to the whole track including info
`encoded` refers to the track info encoded

and `encodedTrack` only has one use in the `Player Update` endpoint as it stands for `track.encoded`
simply having encoded there would be confusing

2022-10-17 16:41 UTC, aikaterna commented on IMPLEMENTATION.md
> +| ping      | int  | The ping of the node to the discord voice server in milliseconds (-1 if not connected) |
```suggestion
| ping      | int  | The ping of the node to the Discord voice server in milliseconds (-1 if not connected) |
```

2022-10-17 16:41 UTC, aikaterna commented on IMPLEMENTATION.md
> +| [WebSocketClosedEvent](#websocketclosedevent) | Emitted when the websocket connection to discord voice servers is closed |
```suggestion
| [WebSocketClosedEvent](#websocketclosedevent) | Emitted when the websocket connection to Discord voice servers is closed |
```

2022-10-17 16:41 UTC, aikaterna commented on IMPLEMENTATION.md
> +| byRemote | bool   | If the connection was closed by discord                                                                                           |
```suggestion
| byRemote | bool   | If the connection was closed by Discord                                                                                           |
```

2022-10-17 16:41 UTC, aikaterna commented on IMPLEMENTATION.md
> +| info    | [Track Info](#track-info) object | Info about the track                                                          |
```suggestion
| Field   | Type                             | Description                                                                          |
|---------|----------------------------------|--------------------------------------------------------------------------------------|
| encoded | string                           | The base64 encoded track data                                                        |
| track   | string                           | The base64 encoded track data (DEPRECATED as of v3.7.0 and marked for removal in v4) |
| info    | [Track Info](#track-info) object | Info about the track                                                                 |
```

2022-10-17 16:41 UTC, aikaterna commented on IMPLEMENTATION.md
> +| lowPass?    | [Low Pass](#low-pass) object       | Lets you filter higher frequencies                                                                |
| Field       | Type                               | Description                                                                                         |
|-------------|------------------------------------|-----------------------------------------------------------------------------------------------------|
| volume?     | float                              | Lets you adjust the player volume from 0.0 to 5.0 where 1.0 is 100%. Values >1.0 may cause clipping |
| equalizer?  | array of [Equalizers](#equalizer)  | Lets you adjust 15 different bands                                                                  |
| karaoke?    | [Karaoke](#karaoke)    object      | Lets you eliminate part of a band, usually targeting vocals                                         |
| timescale?  | [Timescale](#timescale) object     | Lets you change the speed, pitch, and rate                                                          |
| tremolo?    | [Tremolo](#tremolo) object         | Lets you create a shuddering effect, where the volume quickly oscillates                            |
| vibrato?    | [Vibrato](#vibrato) object         | Lets you create a shuddering effect, where the pitch quickly oscillates                             |
| rotation?   | [Rotation](#rotation) object       | Lets you rotate the sound around the stereo channels/user headphones aka Audio Panning              |
| distortion? | [Distortion](#distortion) object   | Lets you distort the audio                                                                          |
| channelMix? | [Channel Mix](#channel-mix) object | Lets you mix both channels (left and right)                                                         |
| lowPass?    | [Low Pass](#low-pass) object       | Lets you filter higher frequencies                                                                  |

2022-10-17 16:41 UTC, aikaterna commented on IMPLEMENTATION.md
> +| volume?     | float                              | Lets you adjust the player volume from 0 to 5.0 where 1.0 is 100%. Values >1.0 may cause clipping |
Is there a reason why a filter can accept volumes of 0% -> 500% where the volume op is 0% -> 1000%?

2022-10-17 16:41 UTC, aikaterna commented on IMPLEMENTATION.md
> +| depth?     | float | The vibrato depth 0 < x ≤ 1 |
| Field  | Type  | Description                |
|--------|-------|----------------------------|
| speed? | float | The playback speed 0.0 ≤ x |
| pitch? | float | The pitch 0.0 ≤ x          |
| rate?  | float | The rate 0.0 ≤ x           |

##### Tremolo
Uses amplification to create a shuddering effect, where the volume quickly oscillates.
https://en.wikipedia.org/wiki/File:Fuse_Electronics_Tremolo_MK-III_Quick_Demo.ogv

| Field      | Type  | Description                      |
|------------|-------|----------------------------------|
| frequency? | float | The frequency 0.0 < x            |
| depth?     | float | The tremolo depth 0.0 < x ≤ 1.0  |

##### Vibrato
Similar to tremolo. While tremolo oscillates the volume, vibrato oscillates the pitch.

| Field      | Type  | Description                     |
|------------|-------|---------------------------------|
| frequency? | float | The frequency 0.0 < x ≤ 14.0    |
| depth?     | float | The vibrato depth 0.0 < x ≤ 1.0 |

2022-10-17 17:11 UTC, Drapersniper commented on IMPLEMENTATION.md
> +GET /version
Could we keep a version-agnostic endpoint to query the node version?

The purpose of this would be to handle multiple versions of a node within a library.

This way I for example would be able to know if a node is v3 or v4 etc before fully connecting to it (and guessing the endpoints) and be able to support multiple versions more easily.

While yes I could try to call `/version` and `v3/info` and `v4/info` and try a different one if it errors or returns nothing - ideally I would query `/version` first to know if it is; say 3.6.0, 3.7.0 or 4.0.0 and call the correct endpoints from there.

For graceful compatibility with 3.6.0 and lower this should remain as `/version` and return nothing but the version number.

2022-10-17 17:56 UTC, freyacodes commented on IMPLEMENTATION.md
> +GET /version
Good point, but at the same time I don't like the current response

Perhaps it should just return the major version and nothing else. We can include in the documentation that if it prefixed with `v` then v3 should be assumed.

2022-10-17 18:29 UTC, Drapersniper commented on IMPLEMENTATION.md
> +GET /version
Was hoping to have a version semantic output - just for more easily able to get the version (minors) as a one-op.

The way I see it is if you only return `{version}` as a text output prior to 3.7, `v3` for <4 and `v4` <5 I would then need to do a second follow-up call via `/v3/info` and `/v4/info` to know the full version name.

While that is not a massive issue it does feel unnecessary (making 2 calls in 3.7+) when keeping it as it is would make it doable in 1 call.

2022-10-17 20:50 UTC, Drapersniper commented on IMPLEMENTATION.md
> +| commitTime | string | The commit time of this Lavalink server |
Is this meant to be a string or an int? asking because the Payload below is currently an int - I assume it just a timestamp and in turn an int

2022-10-17 21:58 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +| volume?     | float                              | Lets you adjust the player volume from 0 to 5.0 where 1.0 is 100%. Values >1.0 may cause clipping |
honestly I have no idea where that value comes from. I can't find any limit in lavaplayer. Maybe someone else can help out here

2022-10-17 21:58 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +| commitTime | string | The commit time of this Lavalink server |
this should be an int ty :)

2022-10-17 22:40 UTC, viztea commented on IMPLEMENTATION.md
> +| volume?     | float                              | Lets you adjust the player volume from 0 to 5.0 where 1.0 is 100%. Values >1.0 may cause clipping |
> I can't find any limit in lavaplayer.

The volume op has a limit here: https://github.com/Walkyst/lavaplayer-fork/blob/original/main/src/main/java/com/sedmelluq/discord/lavaplayer/player/DefaultAudioPlayer.java#L290-L292

For why the lavadsp filter has a lower limit you would have to ask Natan

2022-10-17 22:41 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +| volume?     | float                              | Lets you adjust the player volume from 0 to 5.0 where 1.0 is 100%. Values >1.0 may cause clipping |
Yeah I was talking about filter, not the player volume. I found the other one myself already but ty

2022-10-17 22:45 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +| volume?     | float                              | Lets you adjust the player volume from 0 to 5.0 where 1.0 is 100%. Values >1.0 may cause clipping |
the limit is enforced right here
https://github.com/natanbc/lavadsp/blob/master/src/main/java/com/github/natanbc/lavadsp/volume/VolumePcmAudioFilter.java
so that's your reason :)

2022-10-18 07:46 UTC, freyacodes commented on IMPLEMENTATION.md
> +GET /version
Using Semver (https://semver.org/) could also work

2022-10-18 12:51 UTC, Drapersniper commented on IMPLEMENTATION.md
> +GET /version
Just for context Right now with 3.5.1 and 3.6.0 both returns semver responses which is ideal imo - if we ensure to use semver (i.e "3.7.0" and not "v3.7.0" as proposed here), no special handling would be required on lib sides to allow them to parse the version with the regex expression in semver.org - and as long as the git tags remain semver compatible no further changes will ever be needed here.

2022-10-21 22:43 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +GET /version
I undeprecated `/version` 👍🏻

2022-10-21 22:59 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +| encodedTrack? | ?string                            | The encoded track data to play. `null` stops the current track                |
we decided to rename the `track` field in the track events to `encodedTrack` to match the rest of the new api.
this should now be consistent and I hope what you wanted :)

2022-10-22 11:30 UTC, Drapersniper approved these changes

2022-10-23 12:11 UTC, Drapersniper commented on IMPLEMENTATION.md
> +| filters?      | ?[Filters](#filters) object        | The new filters to apply. `null` will reset all filters                       |
if  `filters=null` resets all the filters is it save to assume `{"filters": {"timescale": Null}}` will reset individual filters? unless I missed it nowhere in this doc we specify that.

2022-10-23 12:31 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +| filters?      | ?[Filters](#filters) object        | The new filters to apply. `null` will reset all filters                       |
in the current api the whole filters get overwritten by the `filters`. This is the case here too
just omit it and it will get overwritten. so in this case `filters: {}` acts the same as `filters: null`

2022-10-23 22:20 UTC, Drapersniper commented on IMPLEMENTATION.md
> +GET /v3/decodetrack?track=BASE64
Wondering should track here also be deprecated in favour of encodedTrack? For consistency.

2022-10-23 23:55 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +GET /v3/decodetrack?track=BASE64
not sure if I like camelCase as a query paramter `encoded-track` instead?

2022-10-24 00:12 UTC, Drapersniper commented on IMPLEMENTATION.md
> +GET /v3/decodetrack?track=BASE64
works for me - suggested camelCase for consistency and other endpoints using it (e.g noReplace)

2022-10-24 00:14 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +GET /v3/decodetrack?track=BASE64
Oh yeah we use camelcase there 
Then it's probably fine I guess hm

2022-10-24 09:59 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +| filters?      | ?[Filters](#filters) object        | The new filters to apply. `null` will reset all filters                       |
I updated the docs on this and it should be more clearer now

2022-10-24 11:44 UTC, Drapersniper commented on IMPLEMENTATION.md
> +Updates the player for this guild.
One thing that wasn't immediately obvious - is what are the new ops that give equivalent behaviour to the deprecated websocket ops.

Seek, pause etc - while the fields are optional so I assume that if I send a payload with just position it will seek, just paused it will pause it may benefit users if you are explicit about this and give at least 1 example:

Say previously your send a seek op, now you make a patch call with just the position key or something like that

2022-10-24 11:50 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +Updates the player for this guild.
maybe we should instead highlight this in the significant changes/deprecated op docs?

2022-10-24 11:51 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +Updates the player for this guild.
with the new api you can seek, pause & set filters at the same time as an example

2022-10-24 13:30 UTC, Drapersniper commented on IMPLEMENTATION.md
> +Updates the player for this guild.
> maybe we should instead highlight this in the significant changes/deprecated op docs?
as some sort of migration guide

I think this is a good call.

yeah the fact you can do multiple ops in one go is great - but I can see some people getting confused and thinking they need a full payload (all fields) if they just wanna seek/pause etc (similar to how with filter you need the full filter payload if you wanna add an additional filter on top of the existing)

2022-10-24 15:24 UTC, ooliver1 requested changes
Grammar fixes :smile:, overall API looks good to me.

2022-10-24 15:24 UTC, ooliver1 commented on IMPLEMENTATION.md
> +* WebSocket handshakes should be done with `/v3/websocket`. Handshakes on `/` is now deprecated.
Handshakes on `/` is - uses plural and singular, either
- Handshakes on `/` are
- Handshaking on `/` is

2022-10-24 15:24 UTC, ooliver1 commented on IMPLEMENTATION.md
> +* Removal of `/v3`. `/v4` will still be available
```suggestion
## Future breaking changes for v4
* HTTP endpoints not under a version path (`/v3`, `/v4`) will be removed in v4.
* No WebSocket messages will be accepted by `/v4/websocket`.
* `/v3` will still be available.

## Future breaking changes for v5
* Removal of `/v3`. `/v4` will still be available.
```

2022-10-24 15:24 UTC, ooliver1 commented on IMPLEMENTATION.md
> +the [exception object](#exception-object)  following the same structure as the `LOAD_FAILED` error on [`/loadtracks`](#track-loading)
```suggestion
the [exception object](#exception-object) following the same structure as the `LOAD_FAILED` error on [`/loadtracks`](#track-loading).
```

2022-10-24 15:24 UTC, ooliver1 commented on IMPLEMENTATION.md
> +One problem we noticed is that since JDA is unaware of ratelimits on the bots gateway connection, it would keep adding
What is this change for? The gateway connection is owned by the bot, it isn't multiple bots.

2022-10-24 15:44 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +Updates the player for this guild.
how do you like the changes in https://github.com/freyacodes/Lavalink/commit/d1006033db73a574c5d9457cc899ff01cd348f64 ?

2022-10-27 09:28 UTC, Drapersniper commented on IMPLEMENTATION.md
> +| exception?   | [Exception](#exception-object) object  | The [Exception](#exception-object) this load failed with  | `LOAD_FAILED`                                      |
`exception` is present in the current response for all load result types - I'm not opposed to it but just wanted to mention it

example of the current response:
```json
{
    "loadType": "NO_MATCHES",
    "tracks": [],
    "playlistInfo": {
        "name": "",
        "selectedTrack": 0
    },
    "exception": null
}
```

2022-10-27 09:31 UTC, melike2d commented on IMPLEMENTATION.md
> +| exception?   | [Exception](#exception-object) object  | The [Exception](#exception-object) this load failed with  | `LOAD_FAILED`                                      |
Topi had broke the audio loader and had implemented a quick fix after I talked to him about it, he's not sure how the field omitting is going work quite yet.

2022-10-27 11:33 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +| exception?   | [Exception](#exception-object) object  | The [Exception](#exception-object) this load failed with  | `LOAD_FAILED`                                      |
the json returned in https://github.com/freyacodes/Lavalink/pull/748 should match this documentation. So I'm gonna resolve this as that's not an issue with the proposal but rather the implemenation

2022-10-27 18:55 UTC, Drapersniper commented on IMPLEMENTATION.md
> +| sessionId  | string | The Discord voice session id to authenticate with                                           |
The API is currently returning `sessionID` instead of `sessionId`

2022-10-31 16:53 UTC, aikaterna approved these changes

2022-11-08 23:12 UTC, ooliver1 approved these changes

2022-11-09 15:00 UTC, ooliver1 requested changes

2022-11-09 15:00 UTC, ooliver1 commented on IMPLEMENTATION.md
> +1. Check that you are intercepting **VOICE_SERVER_UPDATE**s to **Lavalink**. Do not edit the event object from Discord.
It is no longer an "event object".

2022-11-09 15:00 UTC, ooliver1 commented on IMPLEMENTATION.md
> +PATCH /v3/sessions/{sessionId}/players/{guildId}?noReplace=true
This should mention that this is used for creating too, or should also accept the `PUT` verb.

2022-11-09 17:40 UTC, Drapersniper commented on IMPLEMENTATION.md
> +PATCH /v3/sessions/{sessionId}/players/{guildId}?noReplace=true
For the benefit of being able to differ from creation and update in the future I think going the PUT route now would avoid unnecessary breakage later even if they are essentially the same now in the future we may want to differ between an update and creation.

2022-11-09 19:31 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +PATCH /v3/sessions/{sessionId}/players/{guildId}?noReplace=true
creation is noted

2022-11-18 16:02 UTC, freyacodes requested changes

2022-11-18 16:02 UTC, freyacodes commented on PLUGINS.md
> +class TestRequestInterceptor implements RestInterceptor {
Would be good to add the `RestInterceptor` import

2022-11-18 16:02 UTC, freyacodes commented on IMPLEMENTATION.md
> +1. Check that you are intercepting **VOICE_SERVER_UPDATE** and **VOICE_STATE_UPDATES**s to **Lavalink**. You only need the `endpoint`, `token` and `session_id`.
```suggestion
1. Check that you are intercepting **VOICE_SERVER_UPDATE**s and **VOICE_STATE_UPDATE**s to **Lavalink**. You only need the `endpoint`, `token`, and `session_id`.
```

2022-11-18 16:02 UTC, freyacodes commented on IMPLEMENTATION.md
> +1. Check that you are intercepting **VOICE_SERVER_UPDATE** and **VOICE_STATE_UPDATES**s to **Lavalink**. You only need the `endpoint`, `token` and `session_id`.
Actually, where are voice state updates even needed?

2022-11-18 16:02 UTC, freyacodes commented on IMPLEMENTATION.md
> +| `bool`    | A boolean value (`true` or `false`) |
This seems very meaningless considering we're using JSON

1. We don't need to define what a boolean is
2. We don't need to define what a string is. And the encoding is whatever the JSON is. We shouldn't have to define that
3. JSON doesn't have multiple number types, nor is it limited to any number of bits

Though it is still useful to distinguish integers from floats in the rest of the documentation.

2022-11-18 16:02 UTC, freyacodes commented on IMPLEMENTATION.md
> +Emitted when an audio web socket (to Discord) is closed.
```suggestion
Emitted when an audio WebSocket (to Discord) is closed.
```

2022-11-18 16:02 UTC, freyacodes commented on IMPLEMENTATION.md
> +| loadType     | [LoadResultType](#load-result-type)    | The type of the result                                    | all                                                |
```suggestion
| Field        | Type                                   | Description                                               | Required Load Type                                    |
|--------------|----------------------------------------|-----------------------------------------------------------|----------------------------------------------------|
| loadType     | [LoadResultType](#load-result-type)    | The type of the result                                    |                                                    |
```

2022-11-18 16:02 UTC, freyacodes commented on IMPLEMENTATION.md
> +When a search prefix is used, the returned `loadType` will be `SEARCH_RESULT`. Note that, disabling the respective source managers renders these search prefixes redundant. Plugins may also implement
```suggestion
When a search prefix is used, the returned `loadType` will be `SEARCH_RESULT`. Note that, disabling the respective source managers renders these search prefixes useless. Plugins may also implement prefixes to allow for more search engines.
```

2022-11-18 16:02 UTC, freyacodes commented on IMPLEMENTATION.md
> +| semver     | string  | The full version of this Lavalink server                                           |
```suggestion
| semver     | string  | The full version string of this Lavalink server                                    |
```

2022-11-18 16:19 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +1. Check that you are intercepting **VOICE_SERVER_UPDATE** and **VOICE_STATE_UPDATES**s to **Lavalink**. You only need the `endpoint`, `token` and `session_id`.
the session id comes from the voice state update

2022-11-18 20:54 UTC, freyacodes approved these changes

2022-11-18 21:00 UTC, merged