Various changes to the API draft
lavalink-devs/Lavalink pull request #764
Opened 2022-10-10 17:54 UTC by freyacodes

This is a pr on top of #750

* Expanded the change list
* Added future changes in v4 and v5
* Moved WS handshake to /v3/websocket
* Changed structure of Track
* Removed Voice Event, replaced with existing Voice State
* Clarify various things
* And more

2022-10-10 19:07 UTC, TopiSenpai requested changes
looks good to me mostly :)

2022-10-10 19:07 UTC, topi314 commented on IMPLEMENTATION.md
> +| ping      | ?int   | Roundtrip latency to the voice gateway. Response only |
I'm not happy with the header name but this should be more clear
```suggestion
| Field     | Type   | Description                                       | Valid Types       |
|-----------|--------|---------------------------------------------------|-------------------|
| token     | string | The Discord voice token to authenticate with      | Request, Response |
| endpoint  | string | The Discord voice endpoint to connect to          | Request, Response |
| sessionId | string | The Discord voice session id to authenticate with | Request, Response |
| connected | ?bool  | Whether the player is connected                   | Request           |
| ping      | ?int   | Roundtrip latency to the voice gateway            | Request           |
```

2022-10-10 19:07 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +<summary>Response</summary>
```suggestion
<summary>Example Payload</summary>
```

2022-10-10 19:07 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +<summary>Response</summary>
```suggestion
<summary>Example Payload</summary>
```

2022-10-11 15:12 UTC, freyacodes commented on IMPLEMENTATION.md
> +| ping      | ?int   | Roundtrip latency to the voice gateway. Response only |
It feels like this adds a lot more information without actually adding anything. I don't personally like this

2022-10-11 15:21 UTC, TopiSenpai commented on IMPLEMENTATION.md
> +| ping      | ?int   | Roundtrip latency to the voice gateway. Response only |
It would be consistent with the other tables in this regard and make it clearer

2022-10-12 11:49 UTC, TopiSenpai approved these changes

2022-10-12 11:49 UTC, merged