config option to disable specific filters
lavalink-devs/Lavalink pull request #779
Opened 2022-11-22 22:09 UTC by TopiSenpai

This adds an option to disable individual filters.
All ilters are enabled by default regardless if they are listed in there

https://github.com/freyacodes/Lavalink/issues/771

2022-11-22 23:04 UTC, Devoxin commented
This seems a little redundant. What's the purpose of disabling filters when clients can opt not to send configuration values for a given filter?

2022-11-22 23:05 UTC, Devoxin requested changes

2022-11-22 23:05 UTC, Devoxin commented on LavalinkServer/src/main/java/lavalink/server/io/WebSocketHandler.kt
> +        if (!filterConfig["equalizer"]!!) return log.warn("Equalizer is disabled in the config, ignoring equalizer op")
```suggestion
        if (filterConfig["equalizer"] == false) return log.warn("Equalizer is disabled in the config, ignoring equalizer op")
```

2022-11-22 23:16 UTC, TopiSenpai commented
See https://github.com/freyacodes/Lavalink/issues/771

2022-11-24 20:27 UTC, Devoxin approved these changes

2022-11-24 21:30 UTC, merged