Adding the custom version of Erela.js!
lavalink-devs/Lavalink pull request #821
Opened 2023-01-28 20:14 UTC by CustomTag

I have implemented a custom version of Erela.js created by Tomato6966. It supports both the REST API and WebSocket, even for users using an older version of Lavalink. The custom version of Erela.js supports both v3 and v4 of the REST API, allowing users to choose which version they prefer, and even v2 if necessary.

Special thanks to Tomato6966 for their updates and improvements.

2023-01-28 21:27 UTC, ooliver1 commented on README.md
> +| [@skyra/audio](https://github.com/skyra-project/audio)                                                | Node.js  | discord.js              | ❌                |Archived                        |
Why was this change made? It is all misaligned now.

2023-01-28 22:17 UTC, CustomTag commented on README.md
> +| [@skyra/audio](https://github.com/skyra-project/audio)                                                | Node.js  | discord.js              | ❌                |Archived                        |
No its not misaligned it just looks like that in the code but not in the Preview

2023-01-28 22:45 UTC, ooliver1 commented on README.md
> +| [@skyra/audio](https://github.com/skyra-project/audio)                                                | Node.js  | discord.js              | ❌                |Archived                        |
That's the point, the table should still work, but it is an unnecessary change.

2023-02-02 18:43 UTC, TopiSenpai requested changes

2023-02-02 18:43 UTC, TopiSenpai commented on README.md
> +| [@skyra/audio](https://github.com/skyra-project/audio)                                                | Node.js  | discord.js              | ❌                |Archived                        |
if you want this merged please fix the alignment, it should also look good in code

2023-02-03 19:54 UTC, CustomTag commented on README.md
> +| [@skyra/audio](https://github.com/skyra-project/audio)                                                | Node.js  | discord.js              | ❌                |Archived                        |
> if you want this merged please fix the alignment, it should also look good in code

I fixed the alignment so you can push the request when ever you feel for it.

2023-02-19 23:24 UTC, closed without merging