Use kotlinx.serialization
lavalink-devs/Lavalink pull request #846
Opened 2023-03-06 23:11 UTC by DRSchlaubi

2023-03-06 23:35 UTC, melike2d requested changes
brief scroll through

2023-03-06 23:35 UTC, melike2d commented on protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/messages.kt
> +    @SerialName("playerEvent")
Did you mean `playerUpdate`?

2023-03-06 23:35 UTC, melike2d commented on protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/player.kt
> +    val connected: Boolean = false,
`connected` and `ping` were removed.

2023-03-07 00:21 UTC, DRSchlaubi commented on protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/messages.kt
> +    @SerialName("playerEvent")
Good catch, however ws payloads are the only untested thing rn anyw

2023-03-07 00:21 UTC, DRSchlaubi commented on protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/player.kt
> +    val connected: Boolean = false,
Got it from IMPLEMENTATION.md, guess that's not up to date, will remove

2023-03-07 23:45 UTC, TopiSenpai commented on settings.gradle.kts
> +    library("ktor-http", "io.ktor", "ktor-http").version("2.2.4")
I don't think ktor is used anywhere rn?

2023-03-07 23:45 UTC, TopiSenpai commented on protocol/src/jvmMain/kotlin/dev/arbjerg/lavalink/protocol/v4/util.kt
> +    loadFailed(Exception.fromFriendlyException(exception))
let's move this into lavalink-server to remove the lavaplayer dependency

2023-03-07 23:45 UTC, TopiSenpai commented on protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/stats.kt
> +interface Stats {
is there any reason for this being an interface?

2023-03-07 23:45 UTC, TopiSenpai commented on protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/filters.kt
> +    val pluginFilters: Map<String, JsonElement> = mutableMapOf()
as discussed with @DRSchlaubi this change is might not be avoidable

2023-03-08 10:11 UTC, DRSchlaubi commented on protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/stats.kt
> +interface Stats {
There is no @JsonUnwrapped so the StatsEvent implements this as well

2023-03-08 11:22 UTC, DRSchlaubi commented on settings.gradle.kts
> +    library("ktor-http", "io.ktor", "ktor-http").version("2.2.4")
good catch

2023-03-08 14:10 UTC, DRSchlaubi commented on protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/filters.kt
> +    val pluginFilters: Map<String, JsonElement> = mutableMapOf()
It would be possible by making a custom serializer but imo it's not worth it, doing it like this also makes it easier for clients to implement it

2023-03-10 12:05 UTC, TopiSenpai commented on LavalinkServer/src/main/java/lavalink/server/io/SocketContext.kt
> +                val event = dev.arbjerg.lavalink.protocol.v4.Message.EmittedEvent.WebSocketClosedEvent(
should prob use an import here
I'd say we import the v3 stuff with an alias
not the v4 stuff

2023-03-10 13:06 UTC, DRSchlaubi commented on LavalinkServer/src/main/java/lavalink/server/io/SocketContext.kt
> +                val event = dev.arbjerg.lavalink.protocol.v4.Message.EmittedEvent.WebSocketClosedEvent(
we need to import sendV4Message with an alias as the "sendV3Message" is a member function of ISocketContext, hwoever I aggree we should use an alias for v3 event classes

2023-03-27 08:50 UTC, TopiSenpai commented on protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/loadResult.kt
> +        data class Data(
shouldnt this use `Playlist` here?

2023-03-27 08:50 UTC, topi314 commented on protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/loadResult.kt
> +        data class Data(
shouldnt this use `Track` here?

2023-03-27 09:09 UTC, DRSchlaubi commented on protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/loadResult.kt
> +        data class Data(
We can, I just did it so it is more consistent with other types

2023-03-27 09:10 UTC, topi314 commented on protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/loadResult.kt
> +        data class Data(
I think it would make sense so people can pass this object around in their code without issue

2023-03-27 09:14 UTC, TopiSenpai commented on protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/loadResult.kt
> +        override val data: Data
can we also just use `List<Track>` here?

2023-03-27 09:29 UTC, DRSchlaubi commented on protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/loadResult.kt
> +        override val data: Data
That would not implement Data

2023-03-27 09:31 UTC, topi314 commented on protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/loadResult.kt
> +        override val data: Data
oh true lol

2023-03-28 07:25 UTC, topi314 commented on protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/loadResult.kt
> +        COMMON,
these also need the `@SerialName` annotation right?

2023-03-28 07:25 UTC, TopiSenpai commented on protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/loadResult.kt
> +    @SerialName("none")
this should be `empty`

2023-03-28 07:25 UTC, TopiSenpai commented on protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/loadResult.kt
> +    SEARCH_RESULT,
this should be `search`

2023-03-28 22:52 UTC, TopiSenpai commented
I updated my client to the discussed & here implemented changes and it seems to be working fine

2023-03-28 23:58 UTC, melike2d commented on protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/messages.kt
> +            enum class AudioTrackEndReason(val mayStartNext: Boolean) {
Enum members are serialized with different names. Refer to v4 IMPLEMENTATION.md

2023-03-29 15:16 UTC, TopiSenpai commented on protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/player.kt
> +data class VoiceState(
they are marked as not optional in the spec

2023-04-01 23:41 UTC, melike2d approved these changes

2023-04-01 23:41 UTC, viztea commented on protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/loadResult.kt
> +    SEARCH_RESULT,
Maybe rename this enum member to `SEARCH`?

2023-05-01 22:18 UTC, Drapersniper commented
The Track search response is currently broken.

```json
{
	"loadType": "search",
	"data": {
		"tracks": []
	}
}
```
is what's being returned when it should be 

```json
{
	"loadType": "search",
	"data": []
}
```

2023-05-07 13:31 UTC, DRSchlaubi commented
> The Track search response is currently broken.
> 
> ```json
> {
> 	"loadType": "search",
> 	"data": {
> 		"tracks": []
> 	}
> }
> ```
> 
> is what's being returned when it should be
> 
> ```json
> {
> 	"loadType": "search",
> 	"data": []
> }
> ```

fixed

2023-05-22 13:03 UTC, TopiSenpai requested changes

2023-05-22 13:03 UTC, topi314 commented on build.gradle.kts
> +        val clean = git.status().isClean || System.getenv("CI") == null
```suggestion
        val clean = git.status().isClean || System.getenv("CI") != null
```

2023-05-22 13:03 UTC, topi314 commented on build.gradle.kts
> +        val clean = git.status().isClean || System.getenv("CI") == null
not sure why this was changed

2023-05-22 20:18 UTC, merged