Unix Persistence Example
lavalink-devs/Lavalink pull request #890
Opened 2023-06-08 18:57 UTC by JustinPanchula

Per discussion in https://discord.com/channels/1082302532421943407/1116430490623283200, I propose to add the persistence example to the readme for Unix-based systems so that the lavalink client does not close immediately on console exit.

2023-06-08 19:04 UTC, topi314 requested changes
can you add some comments (starting with `#`) to some of the lines?

2023-06-08 19:04 UTC, topi314 commented on README.md
> +### Persistence (Unix example)
this should be named something like `Systemd Service`
and we should put this under the binary header, so `####`

2023-06-08 19:15 UTC, JustinPanchula commented on README.md
> +### Persistence (Unix example)
1. Added extra hash to "Persistence (Unix Example)"
2. Renamed "Persistence (Unix Example) to "Systemd Service"
3. Changed from ``toml`` to ``<blank>`` for Github
4. Added comments inside of ``.service`` file

2023-06-08 19:16 UTC, topi314 commented on README.md
> +### Persistence (Unix example)
try `ini` hat should look alright

2023-06-08 19:42 UTC, topi314 requested changes

2023-06-08 19:42 UTC, topi314 commented on README.md
> +ExecStart=java -jar <home/cen/lavalink>/Lavalink.jar
```suggestion
ExecStart=java -jar <home/user/lavalink>/Lavalink.jar>
```

2023-06-08 19:42 UTC, topi314 commented on README.md
> +WorkingDirectory=</home/cen/lavalink>
```suggestion
WorkingDirectory=</home/user/lavalink>
```

2023-06-08 19:42 UTC, topi314 commented on README.md
> +User=<cen>
```suggestion
# The user as which lavalink should run
User=<cen>
```

2023-06-08 19:46 UTC, JustinPanchula commented on README.md
> +WorkingDirectory=</home/cen/lavalink>
Committed

2023-06-08 19:46 UTC, JustinPanchula commented on README.md
> +User=<cen>
Committed

2023-06-08 19:49 UTC, topi314 commented on README.md
> +If you want your Lavalink server to run even when the console is closed, you will need to create a `.service` file inside of your system's directory (commonly located at `/usr/lib/systemd/system`).
```suggestion
If you want your Lavalink server to run even when the console is closed, you will need to create a `lavalink.service` file inside of your system's directory (commonly located at `/usr/lib/systemd/system`).  Create the file, then add the following components (replacing the text inside "<>" with your values):
```

2023-06-08 19:54 UTC, freyacodes requested changes
I'm inclined to split this and the Docker instructions into different files linked from the readme

2023-06-08 19:54 UTC, freyacodes commented on README.md
> +# The user as which Lavalink should run
```suggestion
# The user which will run Lavalink
```

2023-06-08 19:54 UTC, freyacodes commented on README.md
> +Type=forking
```suggestion
Type=simple
```

Simple seems to be the best for Lavalink. The above comments seem confusing. I'm not sure thread is the right term

2023-06-08 19:54 UTC, freyacodes commented on README.md
> +# Start this service ss part of normal system start-up
```suggestion
# Start this service as part of normal system start-up
```

2023-06-08 19:54 UTC, freyacodes commented on README.md
> +# Restart the service if it closes
```suggestion
# Restart the service if it crashes
```

2023-06-08 19:54 UTC, freyacodes commented on README.md
> +into the console.
```suggestion
To initiate the service, run: 
```shell
sudo systemctl daemon-reload
sudo systemctl enable lavalink.service
sudo systemctl start lavalink.service
```

```

2023-06-08 19:56 UTC, freyacodes commented on README.md
> +into the console.
GitHub suggestions are quite awkward when they contain markdown code blocks

2023-06-08 19:59 UTC, JustinPanchula commented on README.md
> +If you want your Lavalink server to run even when the console is closed, you will need to create a `.service` file inside of your system's directory (commonly located at `/usr/lib/systemd/system`).
Committed

2023-06-08 20:01 UTC, JustinPanchula commented on README.md
> +Type=forking
I'm testing it live rn and I'll get back to you on the results.  I also believe that simple will be the best choice after reading [this article](https://superuser.com/questions/1274901/systemd-forking-vs-simple)

2023-06-08 20:01 UTC, JustinPanchula commented on README.md
> +# Start this service ss part of normal system start-up
Changed.

2023-06-08 20:10 UTC, JustinPanchula commented on README.md
> +# Restart the service if it closes
Changed.

2023-06-08 20:10 UTC, JustinPanchula commented on README.md
> +into the console.
Changed.

2023-06-08 20:10 UTC, JustinPanchula commented on README.md
> +# The user as which Lavalink should run
Changed.

2023-06-08 20:18 UTC, JustinPanchula commented on README.md
> +Type=forking
Can confirm, simple is correct

2023-06-08 23:21 UTC, freyacodes requested changes

2023-06-08 23:21 UTC, freyacodes commented on README.md
> +#   Forking: The service daemonizes itself and there is no need for systemd for to `fork()` it
Referring to forking will only serve to confuse users. The user will probably never want to change this line
```suggestion
```

2023-06-08 23:21 UTC, freyacodes commented on README.md
> +# The user whick will run Lavalink
```suggestion
# The user which will run Lavalink
```

2023-06-08 23:21 UTC, freyacodes commented on README.md
> +into the console.
I still suggest removing `.service`

2023-06-09 02:25 UTC, JustinPanchula commented on README.md
> +into the console.
Yeah, I've removed the ``.service`` marker

2023-06-09 02:25 UTC, JustinPanchula commented on README.md
> +# The user whick will run Lavalink
Grammer corrected

2023-06-09 15:06 UTC, JustinPanchula commented on README.md
> +#   Forking: The service daemonizes itself and there is no need for systemd for to `fork()` it
Fixed.

2023-06-10 10:02 UTC, Drapersniper commented on README.md
> +ExecStart=java -jar </home/cen/lavalink>/Lavalink.jar
should the ram usage flags be added here too? to mirror the docker file usage

2023-06-10 13:25 UTC, freyacodes commented on README.md
> +ExecStart=java -jar </home/cen/lavalink>/Lavalink.jar
Yes

2023-06-10 20:16 UTC, JustinPanchula commented on README.md
> +ExecStart=java -jar </home/cen/lavalink>/Lavalink.jar
Added.

2023-06-10 20:22 UTC, ooliver1 commented
6G seems a bit excessive, why not 4G like the dockerfile

2023-06-10 20:54 UTC, Drapersniper commented on README.md
> +ExecStart=java -jar </home/cen/lavalink>/Lavalink.jar
You should add a comment educating users about this flag too as not all systems can have it set as 4G.

2023-06-12 12:36 UTC, JustinPanchula commented
> 6G seems a bit excessive for an example, why not 4G like the dockerfile

From the current docs, the java memory options in the docker setup lists 6G

2023-06-12 13:18 UTC, ooliver1 commented
> From the current docs, the java memory options in the docker setup lists 6G

https://github.com/lavalink-devs/Lavalink/blob/31ade9087574adf3e657a5f52ed6eeb7c22a5486/LavalinkServer/docker/Dockerfile#L15

2023-06-12 13:44 UTC, topi314 commented
they are referring to this: https://github.com/lavalink-devs/Lavalink#docker

2023-06-12 15:53 UTC, JustinPanchula commented
So are we going with `-Xmx6G` or `-Xmx4G`

2023-06-14 01:31 UTC, JustinPanchula commented
Updated to 4G memory option @ooliver1

2023-06-19 07:32 UTC, topi314 requested changes

2023-06-19 07:32 UTC, topi314 commented on README.md
> +
```suggestion
# Delay each restart by 5s
RestartSec=5s

```

2023-06-19 07:32 UTC, topi314 commented on README.md
> +
```suggestion
# The group which will run Lavalink
Group=<usr>
```

2023-06-19 07:34 UTC, topi314 commented on README.md
> +
```suggestion
To see lavalink logs just run `sudo journalctl -u lavalink` or `tail -f </home/usr/lavalink>/logs/spring.log`
```

2023-06-28 00:16 UTC, topi314 approved these changes

2023-06-29 20:23 UTC, freyacodes requested changes

2023-06-29 20:23 UTC, freyacodes commented on README.md
> +If you want your Lavalink server to run even when the console is closed, you will need to create a `lavalink.service` file inside of your system's directory (commonly located at `/usr/lib/systemd/sys
```suggestion
If you're using a Systemd-based Linux distribution you may want to install Lavalink as a background service. You will need to create a `lavalink.service` file inside `/usr/lib/systemd/system`. Create the file with the following template (replacing the values inside the `<>` brackets):
```

2023-06-29 20:23 UTC, freyacodes commented on README.md
> +# Type of serivce (either simple or forking). DO NOT CHANGE THIS PARAMETER
```suggestion
```

2023-06-29 20:23 UTC, freyacodes commented on README.md
> +To see lavalink logs just run `sudo journalctl -u lavalink` or `tail -f </home/usr/lavalink>/logs/spring.log`
```suggestion
In addition to the usual log files, you can also view the log with `sudo journalctl -u lavalink`.
```

2023-06-29 20:26 UTC, JustinPanchula commented on README.md
> +# Type of serivce (either simple or forking). DO NOT CHANGE THIS PARAMETER
Previously it was discussed that we try to comment out everything in the example so a novice user can more clearly understand what each parameter is.  Is there a replacement comment you'd like here instead?

2023-06-29 21:32 UTC, freyacodes commented on README.md
> +# Type of serivce (either simple or forking). DO NOT CHANGE THIS PARAMETER
That sounds like a miscommunication. Earlier I was suggesting the complete removal of the comment. It is still misleading to present `forking` as an option. Alternatively we could remove the type configuration entirely, as `simple` is apparently the default anyways.

2023-07-07 16:03 UTC, JustinPanchula commented on README.md
> +# Type of serivce (either simple or forking). DO NOT CHANGE THIS PARAMETER
I think removing it entirely is a good option then, I'll update it when I'm back on my home setup

2023-07-07 16:22 UTC, JustinPanchula commented on README.md
> +# Type of serivce (either simple or forking). DO NOT CHANGE THIS PARAMETER
Fixed!

2023-07-07 18:25 UTC, duncte123 commented on README.md
> +    - [Systemd Serivce](#systemd-service)
This seems to be indented a little too much. should it be a sub-chapter of "Binary"?

2023-07-07 18:27 UTC, Tomato6966 commented
It can also be run via "pm2" (process manager intended for node processes but works for other processes too)

like that: 
```
pm2 start java --name "Lavalink Node Process Name of your choice" --max-memory-restart 5G -- -jar Lavalink.jar
```

2023-07-07 18:34 UTC, topi314 commented
I absolutely don't want to encourage people to run lavalink with pm2

2023-07-10 14:39 UTC, JustinPanchula commented on README.md
> +    - [Systemd Serivce](#systemd-service)
Does @topi314's thumbs up mean it should be a sub-chapter or it should be moved up a level?

2023-07-10 14:40 UTC, topi314 commented on README.md
> +    - [Systemd Serivce](#systemd-service)
it should be on the same page as binary so `###` and not `####`

2023-07-11 00:27 UTC, JustinPanchula commented on README.md
> +    - [Systemd Serivce](#systemd-service)
done

2023-07-12 16:51 UTC, topi314 commented on README.md
> +#### Systemd Service
```suggestion
### Systemd Service
```

2023-07-13 14:21 UTC, merged

2023-07-13 14:21 UTC, topi314 commented
thank you!