docs
lavalink-devs/Lavalink pull request #944
Opened 2023-08-15 19:20 UTC by topi314

2023-08-25 12:59 UTC, freyacodes reviewed
I will try to provide a comprehensive review when I have the time

2023-08-25 12:59 UTC, freyacodes commented on README.md
With the removal of a lot of documentation here, I believe that we should have a "Getting started" section that links to server configuration docs and a list of clients. Possibly even with a reference to the API, in case someone needs to implement their own client.

2023-08-25 13:21 UTC, topi314 commented on README.md
we already have that https://lavalink.dev/getting-started/index.html

2023-08-25 13:28 UTC, freyacodes commented on README.md
If a user's entry point is our readme here on GitHub, then I think we need that information to be there

2023-08-25 13:28 UTC, topi314 commented on README.md
tbh, I'd rather just link to our website for this

2023-08-28 10:07 UTC, freyacodes commented on README.md
I'd imagine that it would just be a very small section that links to the appropriate sections of the documentation in a concise manner. Would you mind if I drafted a suggestion?

2023-08-28 10:09 UTC, topi314 commented on README.md
nope, go ahead

2023-09-28 23:08 UTC, freyacodes requested changes
Sorry about the long wait. I've added that draft I mentioned earlier. Some of the changes I've proposed are significant. I hope you will consider them, even if you have already invested a lot of work into this.

2023-09-28 23:08 UTC, freyacodes commented on README.md
> +
```suggestion
## Getting started
* Pick one of the [up-to-date clients](https://lavalink.dev/clients). Advanced users can create their own using the [API documentation
](https://lavalink.dev/api/)
* See the [server configuration documentation](https://lavalink.dev/configuration/) for configuring your Lavalink server
* Explore [available plugins](https://lavalink.dev/plugins) for extra features
* See also our [FAQ](https://lavalink.dev/getting-started/faq)
```

2023-09-28 23:08 UTC, freyacodes commented on docs/api/index.md
> +## Significant changes
This could perhaps be split to a different page

2023-09-28 23:08 UTC, freyacodes commented on docs/api/index.md
> +How to write your own client.
This page doesn't contain a guide on writing a client, so the intro here is a bit misleading.

I think this page should be written to serve these purposes:
* Give a basic overview of the HTTP and WS APIs, and explain why they both exist
* Point users at those relevant pages in the sidebar. I was initially confused when I saw this page
* Provide a general reference that applies to both protocol, including common types like Track

2023-09-28 23:08 UTC, freyacodes commented on docs/api/index.md
> +## Requirements
```suggestion
## Required capabilities of your Discord library
```

2023-09-28 23:08 UTC, freyacodes commented on docs/api/index.md
> +You can find an [Insomnia](https://insomnia.rest/) collection in the [here](Insomnia.json) which contains all the endpoints and their respective payloads.
This should be moved to REST

2023-09-28 23:08 UTC, freyacodes commented on docs/mkdocs.yml
> +copyright: Copyright &copy; 2017-2021 Lavalink Contributors
This doesn't serve any practical purpose

We could say "Licensed under the MIT license" if you think we need to include an explicit copyright statement.

2023-09-28 23:08 UTC, freyacodes commented on docs/stylesheets/neoteroi-cards.css
> +    border-radius: 8px;
```suggestion
    border-radius: 4px;
```
Make it look not too dissimilar to the other buttons

2023-09-28 23:08 UTC, freyacodes commented on docs/overrides/home.html
I'm not a big fan of the 'Home' page. It seems bare, weirdly proportioned, and feels a bit like a barrier to the documentation. I'm wondering if perhaps we could replace it with something like the 'Getting Started' page, except written to also serve as a introduction with a list of features. So 100% documentation without a landing page.

2023-09-29 12:05 UTC, topi314 commented on docs/api/index.md
> +You can find an [Insomnia](https://insomnia.rest/) collection in the [here](Insomnia.json) which contains all the endpoints and their respective payloads.
since this also includes the websocket endpoint (sadly without any event payloads) I think this is the right place to mention it

that being said I don't think I want to move forward with insomnia since what hey did with their v8 release
You can check their recently closed github issues...
<https://github.com/Kong/insomnia/issues?q=is%3Aissue+is%3Aclosed>

2023-09-29 12:06 UTC, topi314 commented on docs/api/index.md
> +You can find an [Insomnia](https://insomnia.rest/) collection in the [here](Insomnia.json) which contains all the endpoints and their respective payloads.
ideally you would be able to import t into the client of your choice

2023-09-29 12:24 UTC, topi314 commented on docs/overrides/home.html
that sounds like I decent idea, I'll play around with it 👍🏻

2023-09-29 12:24 UTC, topi314 commented on docs/api/index.md
> +## Significant changes
perhaps this should be part of the changelog page?

2023-09-29 21:27 UTC, freyacodes commented on docs/api/index.md
> +## Significant changes
Yes

2023-09-29 21:33 UTC, freyacodes commented on docs/api/index.md
> +You can find an [Insomnia](https://insomnia.rest/) collection in the [here](Insomnia.json) which contains all the endpoints and their respective payloads.
Yikes.

But anyways, what does the collection provide which is relevant for WS?

> ideally you would be able to import it into the client of your choice

Like https://www.openapis.org/ ?

2023-09-29 21:36 UTC, freyacodes reviewed
The last 5 commits look good :+1:

2023-09-29 21:39 UTC, topi314 commented on docs/api/index.md
> +You can find an [Insomnia](https://insomnia.rest/) collection in the [here](Insomnia.json) which contains all the endpoints and their respective payloads.
Actually, we completely removed websocket messages sent from the client so no payloads needed there

Anyway opening a lavalink session to test can be quite helpful in some cases
I use it for testing pretty often

An openapi spec would be a big step forward from a simple request collection I'd say

2023-12-02 12:14 UTC, freyacodes approved these changes

2023-12-02 12:14 UTC, merged