Clarify error message about incomplete voice state
lavalink-devs/Lavalink pull request #983
Opened 2023-11-26 12:36 UTC by topi314

2023-11-27 07:53 UTC, duncte123 commented on protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/player.kt
> +    fun copyWithUserData(userData: JsonObject): Track {
Maybe it's a good idea to add "deserializeUserData" like was done in #973 for plugin info

2023-11-27 07:54 UTC, duncte123 commented on protocol/src/commonTest/kotlin/PlayerSerializerTest.kt
> +        val json = """{"track": {"encodedTrack":  "", "identifier":  ""}}"""
Invalid json property
```suggestion
        val json = """{"track": {"encoded":  "", "identifier":  ""}}"""
```

2023-12-02 11:44 UTC, freyacodes requested changes
Documentation is needed

2023-12-02 11:44 UTC, freyacodes commented on LavalinkServer/src/main/java/lavalink/server/player/PlayerRestHandler.kt
> +        } else {
We should return 400 Bad Request if both methods of specification are used

2023-12-02 11:53 UTC, topi314 commented
docs are here https://github.com/lavalink-devs/Lavalink/pull/984

2023-12-02 12:25 UTC, freyacodes approved these changes

2023-12-02 12:50 UTC, duncte123 approved these changes

2023-12-02 12:50 UTC, merged