add docs for track user data
lavalink-devs/Lavalink pull request #984
Opened 2023-11-26 21:45 UTC by topi314

2023-11-27 06:11 UTC, duncte123 requested changes

2023-11-27 06:11 UTC, duncte123 commented on docs/api/rest.md
> +| pluginInfo | object                           | Addition track info provided by plugins                                       |
This feels like a typo

```suggestion
| pluginInfo | object                           | Additional track info provided by plugins                                       |
```

2023-11-27 06:11 UTC, duncte123 commented on docs/api/rest.md
> +| pluginInfo | object                           | Addition track info provided by plugins                                       |
This feels like a typo

```suggestion
| pluginInfo | object                           | Additional track info provided by plugins                                       |
```

2023-11-27 06:11 UTC, duncte123 commented on docs/api/rest.md
> +| userData   | object                           | Addition track data provided via the [Update Player](#update-player) endpoint |
```suggestion
| userData   | object                           | Additional track data provided via the [Update Player](#update-player) endpoint |
```

2023-11-27 06:11 UTC, duncte123 commented on docs/api/rest.md
> +| userData   | object                           | Addition track data provided via the [Update Player](#update-player) endpoint |
```suggestion
| userData   | object                           | Additional track data provided via the [Update Player](#update-player) endpoint |
```

2023-12-02 12:02 UTC, freyacodes requested changes

2023-12-02 12:02 UTC, freyacodes commented on docs/api/rest.md
> -| identifier? *   | string                             | The identifier of the track to play                                                           |
These are deprecated, but I think it is still important to mention them

2023-12-02 12:02 UTC, freyacodes commented on docs/api/rest.md
> +| track?        | [Update Player Track](#update-player-track) | The `encoded` track, `identifier` and `userData` of the track to play                         |
```suggestion
| track?        | [Update Player Track](#update-player-track) | Specification for a new track to load, as well as user data to set                       |
```

2023-12-02 13:05 UTC, duncte123 commented on docs/api/rest.md
> -| identifier? *   | string                             | The identifier of the track to play                                                           |
I agree with Freya here

2023-12-02 13:10 UTC, topi314 commented on docs/api/rest.md
> -| identifier? *   | string                             | The identifier of the track to play                                                           |
done
![image](https://github.com/lavalink-devs/Lavalink/assets/15636011/9c86be32-61cd-4542-b78b-8abf0557f0a2)

2023-12-02 13:13 UTC, merged